### ISSUE TITLE
SEC-4896 - reflected XSS on /gallery/video/0/edit?videoLink=

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#100]
There is reflected XSS on /gallery/video/0/edit?videoLink= endpoint.

Steps to Reproduce:
* login to partner.acronis.com
* Go to https://partners.acronis.com/gallery/video/0/edit?videoLink=https://google.com%27;+alert(document.domain);// and see JS executed

Fix: encode untrusted input according to the rendering context

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have checked above security issue, when we edit any video the default url is "https://main.dvl.amp.vg/gallery/video/6491/edit" and not the one mentioned above.
Kindly provide additional Info or screen recording so that i can reproduce issue on my end.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client to provide more details.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx, Acronis researchers replied that this link was found in the JS file, https://partners.acronis.com/v4u/js/prod.js: 
![scrot_selection_Sep092022_145407](https://user-images.githubusercontent.com/31324885/189411414-c14b2331-7500-462e-880f-7439c806a7ba.png)

**Comment by IshantRevclerx** [comment]
As discuss with @shivmishra sir assigning above ticket to him.

**Comment by shivmishra** [comment]
@IshantRevclerx plz check here https://github.com/MindMatrix/AMP/pull/52699

**Comment by IshantRevclerx** [comment]
@shivmishra sir, @sunrao sir, I have checked above security issue and basic functionality on the given branch ( https://pr-52699.dvl.amp.vg/ ) and It's working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis production and It's working as expected now.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client to confirm.

**Comment by prashantjadhav92** [comment]
The client has confirmed the fix.
