### ISSUE TITLE
SEC-4899 - IDOR on POST /api/SaveOrganization allows access to any file of other organizations

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#101]
IDOR on POST /api/SaveOrganization allows access to any file of other organizations

Steps to Reproduce

Login https://partners.acronis.com/login
Visit this link https://partners.acronis.com/#setup/users/list
Click on the org name
Click views then click on the Info tab
Click Save

Now it is required to repeat POST request to /api/SaveOrganization with changed values for parameters photoid1, photoid2, photoid3, photoid4, photoid5, photoid6, f_50, f_51, f_52, f_53. It is required to set them to id of files in other organizations
Open     view-source:https://partners.acronis.com/setup/organization/info/[your_org_ID]/1659281717667?isorgedit=undefined (set correct [your_org_id] value and see direct links to files

Fix: It must not be possible to access data of other organizations

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, In the api/SaveOrganization, we are not getting the following parameters photoid1, photoid2, photoid3, photoid4, photoid5, photoid6, f_50, f_51, f_52, f_53.
Kindly confirm.

**Comment by shivmishra** [comment]
even we can fix for static column from photoid1, photoid2, photoid3, photoid4, photoid5, photoid6 but not for custom columns f_50, f_51, f_52, f_53.

**Comment by shivmishra** [comment]
for static fields photoid1, photoid2, photoid3, photoid4, photoid5, photoid6 should be fixed in
https://github.com/MindMatrix/AMP/pull/51821 PR. please check

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, @sunrao sir, I have checked above security issue and basic functionality on the given branch (pr-51821.dvl.amp.vg) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx I have asked the client to verify this.

**Comment by prashantjadhav92** [comment]
@shivmishra @shaileshtayde can we have this fixed for f_50, f_51, f_52, f_53 parameters?

**Comment by shivmishra** [comment]
no, only fixed for static columns

**Comment by shivmishra** [comment]
@PuneetRevclerx @prashantjadhav92 this should be fixed in https://github.com/MindMatrix/AMP/pull/52057 PR
Please have this tested

**Comment by PuneetRevclerx** [comment]
@sunrao sir, @shivmishra sir, I have checked the above security issue and basic functionality on the given branch (https://pr-52057.dvl.amp.vg/) and the user is not able to access the files of other organization's users through custom fields as well.

**Comment by shivmishra** [comment]
@sunrao @PuneetRevclerx @IshantRevclerx @prashantjadhav92  that custom fixed issue should be fixed for all type so plz go through across

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify this.

**Comment by prashantjadhav92** [comment]
Verified by the client.
