### ISSUE TITLE
SEC-4904 - IDOR on /communicate/email/[EMAIL_ID]/links?ispartner=true

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#105]
IDOR on /communicate/email/[EMAIL_ID]/links?ispartner=true allowing to access email attachments of other organizations.

Steps to Reproduce:
1. Go to https://partners.acronis.com/#communicate/email
2. Copy an email_id of any email blast
3. Login to another organization
4. Go to https://partners.acronis.com/#communicate/email -> choose any email blast -> click view -> links
5. There will be request to  /communicate/email/[EMAIL_ID]/links?ispartner=true. Repeat this request with [EMAIL_ID] set to id copied on step (2). See links to attachments of email from another organization

Fix: it must not be possible to access data of other organizations

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked the above security issue and by following above mentioned steps user can access the links of email id created by other organization's user.

User: security ishant
Company: Automation testers

**Comment by Mahimapatil** [comment]
@sunrao @IshantRevclerx Also check this issue in same branch
 https://pr-51803.dvl.amp.vg/

**Comment by IshantRevclerx** [comment]
@Mahimapatil mam, @sunrao Sir, I have checked above security issue and basic functionality on the given branch ( https://pr-51803.dvl.amp.vg/ ) and It's working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir,  I have checked above security issue on Acronis production and its working as expected now.

**Comment by prashantjadhav92** [comment]
Verified by the client.
