### ISSUE TITLE
SEC-4922 - IDOR on /api/SetAssetFilterCategoryLinks API endpoint

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#106]
IDOR on /api/SetAssetFilterCategoryLinks API endpoint allowing to set filter for files located in other organizations.

Steps to reproduce:
Make the following request with linkId set to file id from another organization and filterid to any filter

POST /api/SetAssetFilterCategoryLinks HTTP/2
Host: partners.acronis.com
Cookie: .ASPXAUTH=<session>;
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: ar,en;q=0.7,en-GB;q=0.3
Accept-Encoding: gzip, deflate
Content-Type: application/json; charset=utf-8
X-Csrf-Token: 3f8c2d89-d25a-4d1b-9116-92892f40a3a7
X-Requested-With: XMLHttpRequest
Content-Length: 107
Origin: https://partners.acronis.com
Referer: https://partners.acronis.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Te: trailers {"linkId":73654,"isTemplate":false,`"filterCategorys":[{"filterId":"-3829711086501683323","categoryId":"4"}]}

See that filter for file changed

Fix: it must not be possible to access data of other organizations

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have checked above security issue and using above mentioned steps, user can set the filters created by other organization's user.
User Name : security ishant
Company Name : Automation Testers

**Comment by shaileshtayde** [comment]
@pKanth a user can access a record (linkId) from the other organization and assign any filter to it.
There is no permission check for linkid, that needs to be fixed.

**Comment by shivmishra** [comment]
https://github.com/MindMatrix/AMP/pull/51890

**Comment by shivmishra** [comment]
i fixed it

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, @sunrao Sir, I have checked above security issue  and basic functionality on the given branch ( https://pr-51890.dvl.amp.vg/login) and It's working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have verified the above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify.
