### ISSUE TITLE
SEC-4916 - IDOR on /api/GetEmailOpenedUsers API endpoint

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#107]
IDOR on /api/GetEmailOpenedUsers API endpoint

Steps to reproduce:
In the request to /api/GetEmailOpenedUsers change emailid value to id of email from another organization

POST /api/GetEmailOpenedUsers HTTP/2
Host: partners.acronis.com
Cookie: .ASPXAUTH=<session>;
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: ar,en;q=0.7,en-GB;q=0.3
Accept-Encoding: gzip, deflate
Content-Type: application/json; charset=utf-8
X-Csrf-Token: 3f8c2d89-d25a-4d1b-9116-92892f40a3a7
X-Requested-With: XMLHttpRequest
Content-Length: 521
Origin: https://partners.acronis.com
Referer: https://partners.acronis.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Te: trailers {"page":0,"pageSize":15,"sort":"lastlogindate","ascending":false,"filters":[],"condition":false,"format":4,"startdate":"","enddate":"","folder":{"sort":["lastlogindate","users.email","contactcompany"],"viewindex":-1,"name":"","apidata":{"emailid":26397,"currentuser":true,"cstatus":3,"ispartnercontact":true,"name":"Email-new email","filetype":8320,"onbehalfforexport":"114875"}},"emailid":26397,"currentuser":true,"cstatus":3,"ispartnercontact":true,"name":"Email-new email","filetype":8320,"onbehalfforexport":"114875"}

Fix: it must not be possible to access data of other organizations

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have verified above issue and user is able to see the details of users who have opened the email by following the above steps.

**Comment by Mahimapatil** [comment]
@sunrao Done in https://pr-51803.dvl.amp.vg/

**Comment by PuneetRevclerx** [comment]
@Mahimapatil mam, @sunrao sir, I have checked above security issue and basic functionality on the given branch (https://pr-51803.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify the same.

**Comment by prashantjadhav92** [comment]
Verified by the client.
