### ISSUE TITLE
SEC-4914 - IDOR via /api/getListAndPrograms endpoint

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#108]
IDOR via /api/getListAndPrograms endpoint

Steps to Reproduce:
In the following request replace id to the id of contact from another organization and see email address accessible:

POST /api/getListAndPrograms HTTP/2
Host: partners.acronis.com
Cookie: .ASPXAUTH=<session>;
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: ar,en;q=0.7,en-GB;q=0.3
Accept-Encoding: gzip, deflate
Content-Type: application/json; charset=utf-8
X-Csrf-Token: 3f8c2d89-d25a-4d1b-9116-92892f40a3a7
X-Requested-With: XMLHttpRequest
Content-Length: 9
Origin: https://partners.acronis.com
Referer: https://partners.acronis.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Te: trailers

{"id":12}

Fix: it must not be possible to access data of other organizations

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, kindly confirm where this API is getting called?

**Comment by shaileshtayde** [comment]
@PuneetRevclerx /connections/contacts/stats/{Contact_ID}

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, above issue has been fixed and verified on acronis production. User is able to see details of his own contacts and not able to see the details of contacts created by other organization's user.
![image](https://user-images.githubusercontent.com/102346181/186482238-96f3cca3-9708-4128-9f90-8ac53221b753.png)

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx I have asked the Acronis team to verify.

**Comment by prashantjadhav92** [comment]
Verified by the client.
