### ISSUE TITLE
SEC-4921 - IDOR on /manage/campaigns/socialdrip/info/<drip_id>/

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#109]
IDOR on /manage/campaigns/socialdrip/info/<drip_id>/ via <drip_id> parameter.

Steps to reproduce:
https://partners.acronis.com/manage/campaigns/socialdrip/info/<drip_id>/ - replace <drip_id> to id of social drip from any other organization and see data accessible, e.g:
https://partners.acronis.com/manage/campaigns/socialdrip/info/3980/

Fix: it must not be possible to access data of other organizations

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have checked above security issue and user is able to acces the social drip created by other organization's user by changing the punlishing id in the URL.

User Name : Security Ishant
Company Name : Automation Testers

**Comment by steffisam** [comment]
@IshantRevclerx it is fixed can u please check.
url :https://pr-51895.dvl.amp.vg/

**Comment by IshantRevclerx** [comment]
@steffisam, @tajindersharma Sir, I have checked above security issue on the given branch ( https://pr-51895.dvl.amp.vg/) If we add social drip id of other organization user in the URL, then page shows data as shown in the screensht below instead of showing a blank page or Error message.

![image](https://user-images.githubusercontent.com/92088937/187604991-ad1b3752-505f-49c7-b9d5-ebd9ddbe4ccd.png)

**Comment by steffisam** [comment]
@IshantRevclerx  it is working fine on sandbox can you please check. 
url :https://emailtest.sb.amp.vg/#manage/campaigns/socialdrip

**Comment by IshantRevclerx** [comment]
@steffisam, Do we need to signoff this issue on the given PR or on Sandbox.

**Comment by steffisam** [comment]
@IshantRevclerx In the given PR

**Comment by IshantRevclerx** [comment]
@steffisam, above issue is still exist on the given PR, I need to verify issue on the given PR in order to signoff the PR.

**Comment by steffisam** [comment]
@IshantRevclerx Sir since dvl is in debug mode it is showing error instead of blank page. It is working as expected on sandbox. So you can sign it off in this PR

**Comment by IshantRevclerx** [comment]
@sunrao Sir, I have checked above security issue and user is not ascces other organization's user social drip info and  as developer mentioned the page is not getting blank as the dvl is in debug mode.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir,  I have checked above issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify this.

**Comment by prashantjadhav92** [comment]
Verified by the client.
