### ISSUE TITLE
SEC-4928 - XSS via filter field on images edit page

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#112]
XSS via filter field on images edit page

Steps to reproduce:
* Go to https://partners.acronis.com/#gallery/banner/images
* Select any image -> edit
* Set the following payload as filter: test\" onmouseover=confirm(456); x=\"x and press enter
* Move mouse over the filter and see XSS payload executed

Fix: encode untrusted input according to the rendering context

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, similar issue (#22)  has already been reported. I have verified that issue and it's currently assigned to the developer. 
Shall we close this issue?

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx they both might look the same but are tested using different endpoints by the client. The steps on both the issues are different.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked both the issues and they are same. In both issues we are implementing XSS on filters in the image gallery. Only difference is, in this ticket we are adding XSS payload directly from the UI by editing the image and in ticket no. 22 we are doing the same process through /api/SetFilters.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx when this is fixed, will it be fixed for both?

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 Yes sir.

**Comment by prashantjadhav92** [comment]
Thanks for confirming, @PuneetRevclerx I will close this case.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx I am reopening this ticket since the client is saying this is still reproducible. Please confirm the same again using the steps mentioned in this ticket.

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, @shivmishra sir, I have checked the above issue again, and after adding the filter in the image edit form when we hover the mouse on it, JS gets executed.
After saving the image then the JS is not getting executed. 
![image](https://user-images.githubusercontent.com/102346181/189571991-cd8b4b7b-3761-4f00-b794-14ba0e24ed36.png)

**Comment by Vinayakvs1994** [comment]
@sunrao sir the image page filter  issue and other pages filter issues are resolved in this branch .Please assign it for the testing.
the links of the pages are mentioned in the PR

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, @sunrao sir, I have checked above security issue and basic functionality on the given branch (https://pr-52281.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify the fix.

**Comment by prashantjadhav92** [comment]
The fix has been verified.
