### ISSUE TITLE
SEC-4940 - IDOR on /connections/projectinfo/<project_id>/info

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#113]
IDOR on /connections/projectinfo/<project_id>/info

Steps to reproduce:
Open view-source:https://partners.acronis.com/connections/projectinfo/<project_id>/info with id of a project from any other organization and see information accessible.
Example: https://partners.acronis.com/connections/projectinfo/145/info

Fix: it must not be possible to access data of other organizations

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have checked above security issue and user can access the projectinfo of other organization's user by following the above mentioned steps.

User Name : security ishant
Comapny Name : Automation Testers

**Comment by MeghanaThakekar** [comment]
@shaileshtayde @sunrao @pKanth - this is because we have permission like "If logged in user has project view permission and logged in user's current company id is similar to the project id then we are allowing to access its info." 
added in below PR

![image](https://user-images.githubusercontent.com/6465588/186424246-da2809ef-b8cf-42a4-9c5c-9c0c05016f0c.png)

**Comment by shaileshtayde** [comment]
@pKanth Can you please look into this.

**Comment by Vishal-Datla** [comment]
@shaileshtayde It should be good in this PR

**Comment by IshantRevclerx** [comment]
@Vishal-Datla sir, @sunrao sir, I have checked above security issue and basic functionality on the given branch (https://pr-51813.dvl.amp.vg/) and it's working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have checked above security issue on Acronis production and its working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify the same.

**Comment by prashantjadhav92** [comment]
Verified by the client.
