### ISSUE TITLE
SEC-4939 - XSS via filter on /#connections/projectinfo/[id]/info

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#114]
XSS via filter on /#connections/projectinfo/[id]/info

Steps to reproduce:
1. Visit this page https://partners.acronis.com/#connections/projectlists
2. Click on any List
3. Click on Info
4. Change the filters param value to XSS\" onmouseover=\"confirm(164)
5. Now visit this page and hover on the payload https://partners.acronis.com/#connections/projectinfo/[id]/info

Fix: encode untrusted input according to the rendering context

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have checked above security issue and Js getting executed by following above mentioned steps.

![image](https://user-images.githubusercontent.com/92088937/186412355-03e8c5da-4f33-46f0-9808-7191c8789257.png)

**Comment by MeghanaThakekar** [comment]
@IshantRevclerx - please  check on main, its working for me
![image](https://user-images.githubusercontent.com/6465588/187377495-043f98cf-39bc-4a21-b399-ad35e92875d5.png)
![image](https://user-images.githubusercontent.com/6465588/187377239-7a7d0dc9-3fc4-4feb-a11a-248f25845564.png)
![image](https://user-images.githubusercontent.com/6465588/187377302-7865834d-13a9-4197-8634-23aec4a69343.png)

**Comment by IshantRevclerx** [comment]
@MeghanaThakekar mam, I have checked above security issue and JS is still getting executed on main by following the above steps.

![image](https://user-images.githubusercontent.com/92088937/187394994-07fffecc-eb40-4232-961f-6a91a80768ee.png)

**Comment by MeghanaThakekar** [comment]
@IshantRevclerx - working on main
![image](https://user-images.githubusercontent.com/6465588/188612144-d01ec469-61a5-406d-85df-54323c501753.png)

**Comment by IshantRevclerx** [comment]
@MeghanaThakekar mam, I have checked above security issue on the given branch

**Comment by MeghanaThakekar** [comment]
@IshantRevclerx - please check in PR https://github.com/MindMatrix/AMP/pull/52281

**Comment by IshantRevclerx** [comment]
@MeghanaThakekar mam, @sunrao Sir, I have checked above security issue and basic functionality on the given branch ( https://pr-52281.dvl.amp.vg/ ) and It's working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir,  I have checked above security issue on Acronis production and it's working as expected.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify the fix.

**Comment by prashantjadhav92** [comment]
The fix has been verified.
