### ISSUE TITLE
SEC-4938 - IDOR via /manage/opportunity-renewal/1/{OPPORTUNITY_ID}?issharepermission=false, /manage/opportunity-update/1/{OPPORTUNITY_ID} and /api/GetOpportunityProductDtls

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#115]
IDOR via /manage/opportunity-renewal/1/{OPPORTUNITY_ID}?issharepermission=false, /manage/opportunity-update/1/{OPPORTUNITY_ID} and /api/GetOpportunityProductDtls

Steps to Reproduce:

* Open https://partners.acronis.com/manage/opportunity-renewal/1/{OPPORTUNITY_ID}?issharepermission=false with id ofopportunity from another organization
* Open https://partners.acronis.com/manage/opportunity-update/1/{OPPORTUNITY_ID} with id of opportunity from another organization
Make the following request with ID of opportunity from another organization:

POST /api/GetOpportunityProductDtls HTTP/2
Host: partners.acronis.com
Cookie: [ COOKIES ]
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json; charset=utf-8
X-Csrf-Token: [ CSRF_TOKEN ]
X-Requested-With: XMLHttpRequest
Content-Length: 38
Origin: https://partners.acronis.com
Referer: https://partners.acronis.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Te: trailers

{"projecttypeid":1,"projectid":{OPPORTUNITY_ID}}

Fix: it must not be possible to access data of other organizations

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, verified it on acronis2.sb.amp.vg/, user from 1 organization can see details of opportunity created by other organization's user.

user "Ishant Kshirsagar" was able to see and update opportunity created by "Security Test User".

**Comment by MeghanaThakekar** [comment]
@prashantjadhav92  @PuneetRevclerx - check on main

**Comment by PuneetRevclerx** [comment]
@MeghanaThakekar mam, above issue can't be verified on main as the above URLs are not available on main, so, I checked it on Acronis production after the Acronis live push which was done yesterday. User is still able to access the opportunity details of other organization's user.

**Comment by MeghanaThakekar** [comment]
@PuneetRevclerx - fixed
branch : https://pr-52090.dvl.amp.vg/

**Comment by PuneetRevclerx** [comment]
@MeghanaThakekar mam, @sunrao sir, I have checked above security issue on Acronis sandbox and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify the fix.

**Comment by prashantjadhav92** [comment]
Fix has been verified by the client.
