### ISSUE TITLE
SEC-4929 - IDOR on /api/SavePublishing allowing access to files from other organizations

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#118]
IDOR on /api/SavePublishing allowing access to files from other organizations

Steps to reproduce:
Make the following request with thumbnailid set to file id from another organization and <drip_id> to any drip id

POST /api/SavePublishing HTTP/2
Host: partners.acronis.com
Cookie: .ASPXAUTH=<session>;
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: ar,en;q=0.7,en-GB;q=0.3
Accept-Encoding: gzip, deflate
Content-Type: application/json; charset=utf-8
X-Csrf-Token: da1eaba7-35c4-4bcb-8d29-5ceaeb50a37f
X-Requested-With: XMLHttpRequest
Content-Length: 81
Origin: https://partners.acronis.com/
Referer: https://partners.acronis.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Te: trailers {"publishingid":<drip_id>,"name":"TEST","desc":"TEST","filters":"X","thumbnailid":<file_id>}

Open view-source:https://partners.acronis.com/#manage/campaigns/socialdrip/info/<drip_id>/ (set correct <drip_id>) and see link to the file

Fix: it must not be possible to access data of other organizations

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have checked above security issue, user is able to access the files of other organization's user.

User name : Security Ishant
Company name : Automation Testers

**Comment by IshantRevclerx** [comment]
@tajindersharma Sir, I have checked above security issue and basic functionality on the given branch ( https://pr-51931.dvl.amp.vg/ ) and Its working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have verified the above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
Verified by the client.
