### ISSUE TITLE
SEC-3955 IDOR on /api/SaveOrganization - it is possible to set any image (even owned by other organizations) as organization photo (01/12/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#12]
Severity: Medium

In the  request to /api/SaveOrganization it is possible to specify file id for organization  photo. File might be located in any organization. As a result, user will be able to access this file

**Comment by shaileshtayde** [comment]
@shivmishra  implement the permission check for _photoid_ in UpdateCustomFields function as mentioned for user profile data.

**Comment by shivmishra** [comment]
should be fixed here https://github.com/MindMatrix/AMP/pull/48326

**Comment by shivmishra** [comment]
save organization should be tested

**Comment by sunrao** [comment]
@Apeksha1 Pl. test this

**Comment by Apeksha1** [comment]
@shivmishra : I am unable to change Organization Logo on this branch even when I tried doing it manually. Can you please have  a look.

**Comment by Apeksha1** [comment]
@shivmishra : Working as expected.

**Comment by Apeksha1** [comment]
@shivmishra : User is still able to set any image even owned by other Organization as Organization Photo.

**Comment by shivmishra** [comment]
plz verify again

**Comment by Apeksha1** [comment]
@shivmishra : I am unable to change the Organization Logo through API

**Comment by Apeksha1** [comment]
@shivmishra : Working as expected.

**Comment by prashantjadhav92** [comment]
Verified by the client.
