### ISSUE TITLE
SEC-4944 - IDOR on /api/AddCalendarEvent

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#120]
IDOR on /api/AddCalendarEvent

Steps to reproduce:

Make the following request, change event id to id of the event from another organization

POST /api/AddCalendarEvent HTTP/2
Host: partners.acronis.com
Cookie:
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json; charset=utf-8
X-Csrf-Token:
X-Requested-With: XMLHttpRequest
Content-Length: 211
Origin: https://partners.acronis.com/
Referer: https://partners.acronis.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Te: trailers {"eventname":"aa","description":"","eventtype":false,"from":"Mon, 01 Aug 2022 17:24:00 GMT","to":"Mon, 01 Aug 2022 23:59:00 GMT","eventcolor":"#404040","calendareventid":{CALENDAR_EVENT_ID},"reminderbyemail":false,"reminder":-1}

See that event was changed

Fix: it must not be possible to access, change or delete data of other organizations

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked above security issue and user is able to change the calendar events created by other organization's users.

User- puneet security
Company- Automation Testers

**Comment by MeghanaThakekar** [comment]
@PuneetRevclerx @prashantjadhav92 - fixed
check on https://pr-51889.dvl.amp.vg/

**Comment by PuneetRevclerx** [comment]
@MeghanaThakekar mam, @sunrao sir, I have checked above security issue and basic functionality on the given branch (https://pr-51889.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 Sir, I have verified the above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
Verified by the client.
