### ISSUE TITLE
SEC-4943 - IDOR on /api/DeleteCalendarEvent

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#121]
IDOR on /api/DeleteCalendarEvent

Steps to reproduce:

Make the following request, change event id to id of the event from another organization

POST /api/DeleteCalendarEvent HTTP/2
Host: partners.acronis.com
Cookie:
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json; charset=utf-8
X-Csrf-Token:
X-Requested-With: XMLHttpRequest
Content-Length: 14
Origin: https://partners.acronis.com
Referer: https://partners.acronis.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Te: trailers {"eventid":{CALENDAR_EVENT_ID}}

See event deleted

Fix: it must not be possible to access, change or delete data in other organizations

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have verified above security ticket, user can delete calenderEvent created other organization's user.

**Comment by MeghanaThakekar** [comment]
@prashantjadhav92 @IshantRevclerx - fixed

**Comment by IshantRevclerx** [comment]
@MeghanaThakekar mam, and @sunrao Sir, i have checked above security issue and basic functionality on the given branch ( https://pr-51889.dvl.amp.vg/ ) and Its working as exepected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have verified the above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
Verified by the client.
