### ISSUE TITLE
SEC-4900 - IDOR on /setup/organization/planning/<org_ID

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#123]
IDOR on GET request to /setup/organization/planning/<org_ID via <org_ID> parameter

Open https://partners.acronis.com/setup/organization/planning/<org_ID> wit h<org_ID> of any other organization. See that data is accessible. Example: https://partners.acronis.com/setup/organization/planning/23112

Fix: It must not be possible to access data of other organizations

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked above security issue and user is able to see the planning of other organizations.

User "puneet security" of "Security 1" organization is able to see the planning of "Automation" organization.

**Comment by HareshKedar** [comment]
@PuneetRevclerx kindly verify on https://pr-52075.dvl.amp.vg/login

**Comment by PuneetRevclerx** [comment]
@HareshKedar sir, @sunrao sir, I have checked the above security issue and basic functionality on the given branch (https://pr-52075.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 Sir, I have verified the above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
Thank you for confirming, Sabina.
