### ISSUE TITLE
SEC-4898 - IDOR on /setup/contact/company/info/{account_id}/false

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#124]
IDOR on /setup/contact/company/info/{account_id}/false

Steps to Reproduce:
In the request to /setup/contact/company/info/{account_id}/false change [account_id] to the ID of the account from another organization and see that data about this account is accessible.
Request to this page is sent from https://partners.acronis.com/#connections/accounts -> any account -> info

Fix: It must not be possible to access data about other organizations

**Comment by sunrao** [comment]
@shaileshtayde verified on MM.AMP.VG by using the URL of https://mm.amp.vg/#setup/contact/company/info/1265132/false (Account created by AP2)

visible for jasmine1_security (user doesn't have contacts permission also)

**Comment by shivmishra** [comment]
@sunrao what permission expected to access any account?

**Comment by shivmishra** [comment]
@IshantRevclerx @sunrao fixed and should be tested here https://github.com/MindMatrix/AMP/pull/51821

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, @sunrao sir, I have checked the above security issue and basic functionality on the given branch (https://pr-51821.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
Verified by the client.
