### ISSUE TITLE
SEC-4902 - IDOR on /api/GetContactsForEmail via emailid parameter

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#125]
IDOR on /api/GetContactsForEmail via emailid parameter

Steps to reproduce:
* with (A) account go to https://partners.acronis.com/#communicate/email and choose any blast you have there
* Click View -> Recipients
* Repeat POST request to /api/GetContactsForEmail with emailid from another organization (in both fields)
* See recipients for email from other organization

Fix: It must not be possible to access data of other organizations

**Comment by shaileshtayde** [comment]
Marked query needs to be fixed**
![image](https://user-images.githubusercontent.com/6465652/186438770-51d824ca-9b39-4cec-80f8-8f3754b7bbe9.png)

**Comment by MeghanaThakekar** [comment]
@shaileshtayde - the issue is because of AssertAccess
![image](https://user-images.githubusercontent.com/6465588/186719195-19e6e8b4-6e2a-486f-a007-13b6f977fdfc.png)
where we are having check 
![image](https://user-images.githubusercontent.com/6465588/186719719-051be28a-975d-4920-84c3-87e2eb1ecb04.png)

@shaileshtayde  updated the code

@IshantRevclerx @prashantjadhav92 - fixed
branch : https://pr-51816.dvl.amp.vg/

**Comment by IshantRevclerx** [comment]
@MeghanaThakekar, @sunrao Sir I have checked above security issue and basic functionality on the given branch ( https://pr-51816.dvl.amp.vg/ ) and Its working as expected now.

**Comment by Mahimapatil** [comment]
@MeghanaThakekar Same with this too.

**Comment by MeghanaThakekar** [comment]
@Mahimapatil - can you mention the specific changes? as this was signed of from my branch

**Comment by Mahimapatil** [comment]
@MeghanaThakekar I have mentioned the PR. The same changes will solve your issues too.

**Comment by MeghanaThakekar** [comment]
@IshantRevclerx - please check in https://pr-51803.dvl.amp.vg/

**Comment by IshantRevclerx** [comment]
@MeghanaThakekar mam, @sunrao Sir, I have checked above security issue and basic functionality on the given branch
 ( https://pr-51803.dvl.amp.vg/ ) and Its working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have checked above security issue on Acronis production and its working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify the same.

**Comment by prashantjadhav92** [comment]
Verified by the client.
