### ISSUE TITLE
SEC-4927 - IDOR on /api/SaveAccount allowing to change account from another organization

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#126]
IDOR on /api/SaveAccount allowing to change account from another organization

Steps to reproduce:
Make the following request. Change accountId value to ID of the account from another organization and send the request

POST /api/SaveAccount HTTP/2
Host: partners.acronis.com
Cookie: [COOKIES]
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json; charset=utf-8
X-Csrf-Token: [CSRF_TOKEN]
X-Requested-With: XMLHttpRequest
Content-Length: 257
Origin: https://partners.acronis.com
Referer: https://partners.acronis.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Te: trailers {"accountID":{ACCOUNT_ID_YOU_WANT_TO_CHANGE},"json":{"name":"2nd","address1":"","address2":"","address3":"","city":"","state":"","zipcode":"","country":"","phone":"","fax":"","websiteurl":"","blogurl":"","twitterurl":"","facebookurl":"","linkedinurl":"","youtubeurl":""},"cfjson":{}}

See account changed

Fix: it must not be possible to access data of other organizations or change it

**Comment by shaileshtayde** [comment]
Permission needs to be fixed
![image](https://user-images.githubusercontent.com/6465652/186437927-db4b7617-fb85-486c-beba-059e3216522f.png)

**Comment by shivmishra** [comment]
@IshantRevclerx @sunrao fixed and should be tested here https://github.com/MindMatrix/AMP/pull/51821

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, @sunrao Sir, I have checked above security issue and basic functionality on the given branch ( https://pr-51821.dvl.amp.vg/ ) and its working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have checked above security issue on Acronis production and its working as expected now.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
Verified by the client.
