### ISSUE TITLE
SEC-4925 - IDOR via /communicate/email/<email_id>/interest

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#128]
IDOR via /communicate/email/<email_id>/interest

Steps to Reproduce:
Open: view-source:https://partners.acronis.com/communicate/email/<email_id>/interest with <email_id> of email in another organization. See data accessible. Example: view-source:https://partners.acronis.com/communicate/email/26535/interest

Fix: it must not be possible to access data of other organizations

**Comment by MeghanaThakekar** [comment]
@IshantRevclerx @prashantjadhav92 @shaileshtayde - fixed
branch : https://pr-51816.dvl.amp.vg/
@sunrao - also check email report section.

**Comment by PuneetRevclerx** [comment]
@MeghanaThakekar mam, @sunrao sir, I have checked above security issue and basic functionality on the given branch (pr-51816.dvl.amp.vg) and it's working as expected now.

**Comment by Mahimapatil** [comment]
@MeghanaThakekar Same with this issue too.

**Comment by MeghanaThakekar** [comment]
@Mahimapatil - can you mention the specific changes? as this was signed of from my branch

**Comment by Mahimapatil** [comment]
@MeghanaThakekar I have mentioned the PR. The same changes will solve your issues too.

**Comment by MeghanaThakekar** [comment]
@IshantRevclerx - please check in https://pr-51803.dvl.amp.vg/

**Comment by IshantRevclerx** [comment]
@Mahimapatil mam, @sunrao Sir, I have checked above security issue and basic functionality on the given branch (https://pr-51803.dvl.amp.vg/) and Its working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir,  I have checked above security issue on Acronis production and its working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify the same.

**Comment by prashantjadhav92** [comment]
Verified by the client.
