### ISSUE TITLE
SEC-4924 - XSS on https://partners.acronis.com/#connections/accounts page in company name

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#129]
XSS on https://partners.acronis.com/#connections/accounts page in company name

Steps to reproduce:
Create contact with XSS payload in company name, xx" onmouseover="confirm(541515)
Go to https://partners.acronis.com/#connections/accounts
Move over company name and see js executed
![scrot_selection_Aug062022_002016](https://user-images.githubusercontent.com/31324885/183725497-a56f190a-33e9-47e1-97f7-80e067506534.png)

Fix: encode untrusted input according to the rendering context

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, above ticket is duplicate #43

**Comment by prashantjadhav92** [comment]
@IshantRevclerx, issue 43 is for the deal page. This issue is reported for the accounts page.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, In both the tickets we are applying XSS in account name field.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx the client has mentioned the issue on #43 is not reproducible anymore but the one mentioned on this ticket is still reproducible. Please check this again as it doesn't seem to be a duplicate issue.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, The above Issue is already addressed in PR- 52057 and the PR is still need to be merged. Once the PR will merge the issue will resolved on production.

**Comment by sunrao** [comment]
https://github.com/MindMatrix/AMP/pull/52057

**Comment by IshantRevclerx** [comment]
@sunrao Sir, @shivmishra Sir,  I have checked above security issue and basic functionality on the given branch (https://pr-52057.dvl.amp.vg/) and it's working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir,  I have checked above issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify this.

**Comment by prashantjadhav92** [comment]
Verified by the client.
