### ISSUE TITLE
SEC-4930 - IDOR on /communicate/email/<email_id>/unsubscribed

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#130]
IDOR on /communicate/email/<email_id>/unsubscribed

Steps to reproduce:
Open view-source:https://partners.acronis.com/communicate/email/<email_id>/unsubscribed with email id from any other organization and see emails of users who are unsubscribed. I believe the same is possible with  bounced (/api/GetBouncedContactsForEmail) and spam (/api/GetSpamEmailContacts) endpoints.
Example: https://partners.acronis.com/communicate/email/26535/unsubscribed

Fix: it must not be possible to access data of other organizations

**Comment by shaileshtayde** [comment]
Verified it 2 different users of 2 diff organizations

**Comment by MeghanaThakekar** [comment]
@IshantRevclerx @prashantjadhav92 @shaileshtayde - fixed
branch : https://pr-51816.dvl.amp.vg/
@sunrao - also check email report section.

**Comment by IshantRevclerx** [comment]
@MeghanaThakekar mam, @sunrao Sir, I have checked above security issue and basic functionality on the given branch ( https://pr-51816.dvl.amp.vg/ ) and its working as expected now.

**Comment by Mahimapatil** [comment]
@MeghanaThakekar This can be fixed by changes in PR https://github.com/MindMatrix/AMP/pull/51803. You can discard your changes for this issue from your branch.

**Comment by MeghanaThakekar** [comment]
@Mahimapatil - can you mention the specific changes? as this was signed of from my branch

**Comment by Mahimapatil** [comment]
@MeghanaThakekar I have mentioned the PR. The same changes will solve your issues too.

**Comment by MeghanaThakekar** [comment]
@IshantRevclerx - please check in https://pr-51803.dvl.amp.vg/

**Comment by IshantRevclerx** [comment]
@MeghanaThakekar mam, @sunrao Sir, I have checked above security issue and basic functionality on the given branch (https://pr-51803.dvl.amp.vg/) and Its working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have checked above security issue on acronis production and its working as expected now.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client to verify this.

**Comment by prashantjadhav92** [comment]
Verified by the client.
