### ISSUE TITLE
SEC-4479 - SXSS in (companyEmail) parameter in Company Settings

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#132]
A Stored-XSS in company settings at [companyEmail] parameter

Steps to reproduce:
1. go to company settings
2. click save to change the settings and intercept the request until you find this endpoint /api/SaveOrganization
3. put this XSS payload https://laz0rde.com\"onmouseover=\"alert('XSS')
4. go again and hover on the [companyEmail] payload and you will see the popup

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked the above security issue and similar issue has already been created (#23) and is already assigned to the developer.

**Comment by prashantjadhav92** [comment]
Similar issue https://github.com/MindMatrix/SecurityTracker/issues/23
