### ISSUE TITLE
SEC-4448 - Stored-XSS via Offline Activity Name

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#133]
Steps To Reproduce:
1. Create Contact
2. Create Offline Activity for the contact with this name: XSS' onmouseover='confirm(164)' x='x
3. Create list then add the contact to the new list
4. Share the list with the victim, whether within the same organization or another organization
5. Visit this page with the victim account: https://partners.acronis.com/#connections/contacts
6. You will notice the contact you created, Click on it
7. Select the report tap
8. Now hover on the XSS payload and you will see the popup

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked above security issue and JS is getting executed by add XSS payload in the offline activity name and then checking it in the report. 
![image](https://user-images.githubusercontent.com/102346181/186411547-ea8677af-9735-4dcd-8cbe-758b1c637632.png)

**Comment by shivmishra** [comment]
fixed here https://github.com/MindMatrix/AMP/pull/51890

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, @sunrao sir, I have checked above security issue and basic functionality on the given branch (https://pr-51890.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 Sir, I have verified the above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
Verified by the client.
