### ISSUE TITLE
SEC-4937 - IDOR on /connections/projectlist/<list_id>/notification endpoint

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#135]
IDOR on /connections/projectlist/<list_id>/notification

Steps to reproduce:
Open view-source:https://partners.acronis.com/connections/projectlist/<list_id>/notification endpoint with list id from any other organization and see notifications settings and to-dos.

Example: https://partners.acronis.com/connections/projectlist/146/notification

Fix: it must not be possible to access data of other organizations

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked the above security issue and user is able to access the notification settings and to-dos of the project list created by other organization's user.

User: puneet security
Company: Automation testers.

**Comment by Vishal-Datla** [comment]
@sunrao @shaileshtayde This is fixed in above PR. Please assign it for testing

**Comment by PuneetRevclerx** [comment]
@Vishal-Datla sir, @sunrao sir, I have checked above security issue and basic functionality on the given branch (https://pr-51813.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify the same.

**Comment by prashantjadhav92** [comment]
Verified by the client.
