### ISSUE TITLE
SEC-4936 - IDOR on /contacts/offline/edit/<id>/1/ endpoint

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#136]
IDOR on /contacts/offline/edit/<id>/1/

Steps to reproduce:
Open view-source:https://partners.acronis.com/contacts/offline/edit/<id>/1/ with activity id from any other organization and see activity of contact from another organization.

Example: https://partners.acronis.com/contacts/offline/edit/52/1/

Fix: it must not be possible to access data of other organizations

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have checked above security issue and user can check the offline activity of other orgnaization's user by following the above mentioned steps.

User Name : Security Ishant 
Company Name : Automation Testers

**Comment by shivmishra** [comment]
https://github.com/MindMatrix/AMP/pull/51890 check here

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, @sunrao Sir, I have checked above security issue and basic functionality on the given branch ( https://pr-51890.dvl.amp.vg/login ) and It's working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have verified the above issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
Verified by the client.
