### ISSUE TITLE
SEC-4931 - IDOR on /communicate/email/<email_id>/unopened

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#137]
POST request to /api/GetUnopenedContactsForEmail, where email id parameter might be changed to id of email in another organization.

Steps to reproduce:
Open

view-source:https://partners.acronis.com/communicate/email/<email_id>/unopened
with email id from any other organization and see emails of users who
are unsubscribed.
Example: https://partners.acronis.com/communicate/email/26535/unopened

Fix: it must not be possible to access data of other organizations

https://user-images.githubusercontent.com/31324885/184016631-6f45b793-0850-492c-b669-3eef4858d403.mp4

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked the above security issue and user can see contacts of other organization's user by following the above mentioned steps

User: puneet security
Company: Automation Testers

**Comment by Mahimapatil** [comment]
@sunrao @sunrao Done in https://pr-51803.dvl.amp.vg/

**Comment by IshantRevclerx** [comment]
@Mahimapatil mam, @sunrao Sir I have checked above security issue and basic functionality on the given branch ( https://pr-51803.dvl.amp.vg/ ) and Its working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir,  I have checked above security issue on Acronis production and its working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify the same.

**Comment by prashantjadhav92** [comment]
Verified by the client.
