### ISSUE TITLE
SEC-4449 - IDOR allows to access all customers files. [Via ThumbnailID Parameter]

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#139]
Steps To Reproduce:

Login https://partners.acronis.com/login
Visit this page https://partners.acronis.com/#gallery/documents/assets
Click edit on any document
Click on the Thumbnail input and choose an image
Intercept the request before click Save .
You will find this API endpoint /api/RenameFile
Change the thumbnailID value to any file ID
Click forward in Burp
Visit this link view-source:https://partners.acronis.com/gallery/documents/[your_doc_ID]/edit/edit
Now you will find the document URL

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have checked above security issue and user can access the images of other organization's user by following the above mentioned steps.

User Name : Security Ishant
Company Name : Automation Testers

**Comment by shivmishra** [comment]
@IshantRevclerx @sunrao fixed and should be tested here https://github.com/MindMatrix/AMP/pull/51821

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, I have checked above security issue on the given branch ( https://pr-51821.dvl.amp.vg/), User is not able to set any of his own image as the thumbnail image of any document from the UI.

**Comment by shivmishra** [comment]
@IshantRevclerx plz check again after build if not working then provide documentid and imageid also to verify

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, User is still

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, User is still not able to set any of his own image as the thumbnail image of any document from the UI.
User Name : Security Ishant
Company Name : Automation Testers
Document ID : 6090
 Image ID : 5939

**Comment by shivmishra** [comment]
@IshantRevclerx check now, that should be fixed

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, @sunrao Sir, I have checked above security issue and basic functionality on the given branch ( https://pr-51821.dvl.amp.vg/) and Its working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have checked above security issue on Acronis production and its working as expected now.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client to verify this.

**Comment by prashantjadhav92** [comment]
Verified by the client.
