### ISSUE TITLE
#1478012 IDOR on  /feedback/<file_ID>/2/rating (02/14/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#14]
Severity: Medium

It is possible to get direct links to files using /feedback/<file_ID>/2/rating endpoint. “Asset Name” will be the link to the file

**Comment by shaileshtayde** [comment]
@shivmishra we'd need to implement permission check in _GetFeedbackRatingForItem_ API + _ratinghistory.aspx.cs_ for resp. file/template id.
Also, please confirm if rating can be visible to any logged-in user?

**Comment by shivmishra** [comment]
@sunrao this is fixed here ask someone to test 
https://github.com/MindMatrix/AMP/pull/48276

**Comment by sunrao** [comment]
@shivmishra Mention the pages to be tested

**Comment by shivmishra** [comment]
its a common rating to rate from diffrent grids

**Comment by sunrao** [comment]
@Apeksha1 Pl. test this

**Comment by shivmishra** [comment]
@Apeksha1 why u checking in security-tracer-2 branch??

**Comment by Apeksha1** [comment]
@shivmishra : Working on expected on  https://dvl-issue-security-tracker.amp.vg/#corporatemarketing branch.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have cheked above mentioned Security Issue and its working fine.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client to confirm.
