### ISSUE TITLE
#1449932 Stored XSS using file renaming

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#141]
It is possible to change uploaded file extension to .svg, which leads to Cross-Site Scripting attack possibility. For example, the following file was uploaded: https://partners.acronis.com/file/ccweldtavhlnc/svg.txt, if extension is changed to .svg, XSS payload will be executed: https://partners.acronis.com/file/ccweldtavhlnc/svg.svg

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked the above security issue on https://partners.acronis.com/#gallery/documents/assets and JS is getting executed if uploaded text file has JS script in it.

User: pemyqy@mailinator.com

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, @sunrao sir, I have checked above security issue and basic functionality on the given branch (https://pr-51890.dvl.amp.vg) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@shivmishra sir I have checked the above security issue on Acronis production and JS is getting executed by following the above-mentioned steps.

![image](https://user-images.githubusercontent.com/102346181/190122066-09284027-cd94-4487-acf2-76ec91449415.png)

It's working as expected on the main.
![image](https://user-images.githubusercontent.com/102346181/190126902-f9f7a4e1-1317-4e1e-ba29-0839c5ce2693.png)

**Comment by shivmishra** [comment]
this should not but can you plz try again in both places in main and acronis

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, I have checked again and on main it's working fine but on Acronis production, JS is still getting executed.

**Comment by shivmishra** [comment]
@shaileshtayde what could be the reason

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, the above issue is reproducible on MM (Live) but not on Main.

**On Main**
![image](https://user-images.githubusercontent.com/102346181/193881810-33eec1eb-5150-449d-97af-bb91fe004e61.png)

**On MM (Live)**
![image](https://user-images.githubusercontent.com/102346181/193881937-83c8de36-5dcd-4bae-8e5a-62c327a03ff9.png)

**Comment by shaileshtayde** [comment]
@IshantRevclerx @PuneetRevclerx kindly provide your feedback on the same

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked the above issue on Acronis production and it's still getting reproduced.

**Comment by shaileshtayde** [comment]
@PuneetRevclerx This is not yet pushed to Acornis production ;) but I had call with @IshantRevclerx yesterday on sandbox, I'll have this reviewed today and get back to you!

**Comment by shaileshtayde** [comment]
@PuneetRevclerx @IshantRevclerx this is fixed and pushed to Acronis sandbox, kindly check the same

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked it on Acronis Sandbox and it's working as expected now.

**Comment by shaileshtayde** [comment]
@IshantRevclerx @PuneetRevclerx have this tested in this branch;
https://github.com/MindMatrix/AMP/pull/55369 > http://pr-55369.dvl.amp.vg/

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, kindly publish this PR on Acronis Sanbox because on dvl I am getting following error message: 
![image](https://user-images.githubusercontent.com/102346181/221148899-11f09a30-1c96-49d5-a58a-dfea1520e39b.png)

**Comment by shaileshtayde** [comment]
@PuneetRevclerx Code is published on Acronis sandbox.

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked it on Acronis Sandbox and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked the above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have requested the client to verify the same on their end.
