### ISSUE TITLE
XSS : JS is getting executed on Opportunity Name and Account name 

### ISSUE THREAD

**Issue by IshantRevclerx** [MindMatrix/SecurityTracker#144]
URL : https://main.dvl.amp.vg/#manage/opportunity-records
User Name : Security Ishant 
Company Name : Automation Testers

STR : 
1) Go to above URL>>> click on create record button>> type ( "onclick=confirm(1)// ) in Opportunity name 
    field and type ("onmouseover=alert(1)//) in Account name field.
 2) Fill the required fields and Click on save button.
3) Hover the mouse on account name or click on opprtunity name on grid page.

Actual Result : JS is getting execute

![image](https://user-images.githubusercontent.com/92088937/188116602-849abbb7-5264-4c81-9af8-59362824a455.png)
Expected Result : JS should not getting executed.

**Comment by shaileshtayde** [comment]
@IshantRevclerx can you please have this checked in this branch => "global-security-fix-dot-template" 
Shiv has fixed the XSS issue globally for all dot-templates; => https://github.com/MindMatrix/AMP/pull/51734

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, on the given branch ( https://pr-51734.dvl.amp.vg/login ), If we open the opportunity page, page gets blank.
![image](https://user-images.githubusercontent.com/92088937/188127553-d52924f8-f4ed-480c-804f-95391ac0fafa.png)

**Comment by MeghanaThakekar** [comment]
@PuneetRevclerx - fixed
branch : https://pr-52090.dvl.amp.vg/

**Comment by PuneetRevclerx** [comment]
@MeghanaThakekar mam, @sunrao sir, I have checked the above security issue and basic functionality on the given branch (https://pr-52090.dvl.amp.vg/) and it's working as expected now.

**Comment by MeghanaThakekar** [comment]
@PuneetRevclerx - please check this issue in pr https://github.com/MindMatrix/AMP/pull/51374

**Comment by prashantjadhav92** [comment]
@IshantRevclerx was this verified?

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, security issue is fixed in PR-51374 , but some functionality and  API's issues are pending.

**Comment by IshantRevclerx** [comment]
@sunrao sir,  I have verified on mm live Production and Its' working as expected.
