### ISSUE TITLE
SEC-5071 - IDOR to mark as done any todo activity from different organization

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#145]
It is possible to mark as Done any ToDO activity from different organizations.

Steps to reproduce:

Send the following request. Replace <SESSION>, <CSRF_TOKEN>, <TODO_ID> and <CONTACT_ID> with appropriate values. <CONTACT_ID> can be any id, it is not used for validation, set <TODO_ID> to ID of ToDo from another organization:

1. curl -X POST https://partners.acronis.com/api/markDoneNotification -H "Content-Type: application/json" -b ".ASPXAUTH=<SESSION>" -H "X-Csrf-Token: <CSRF_TOKEN>" -d '{"id":<TODO_ID>,"contactid":<CONTACT_ID>}'

See that this todo is marked as done

Fix: it must not be possible to change data of other organizations

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have checked above security issue and user is able to mark as Done any ToDO activity of contacts from other organization's user by following above mentioned steps.

**Comment by shivmishra** [comment]
check in this branch https://github.com/MindMatrix/AMP/pull/52387

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, @sunrao Sir, I have checked above security issue and basic functionality on the given branch ( https://pr-52387.dvl.amp.vg) and It's working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir,  I have checked above issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify this.

**Comment by prashantjadhav92** [comment]
Verified by the client.
