### ISSUE TITLE
SEC-5076 - IDOR that allows to access information about contacts from other organizations, /api/GetContact

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#147]
IDOR that allows to access information about contacts from other organizations. Endpoint /api/GetContact is vulnerable

Steps to Reproduce:
Send the following request. Replace <SESSION>, <CSRF_TOKEN> and <CONTACT_ID> with appropriate values. <CONTACT_ID> should be replaced with ID of contact from another organization:

curl -X POST https://partners.acronis.com/api/GetContact -H "Content-Type: application/json" -b ".ASPXAUTH=<SESSION>" -H "X-Csrf-Token: <CSRF_TOKEN>" -d '{"id":<CONTACT_ID>,"cstatus":1,"isroutedlead":false}'

See that information about contact is accessible

Fix: it must not be possible to access data of other organizations

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have checked above security issue and user is able to access the contact details of other organization's user by following above mentioned steps.

**Comment by shivmishra** [comment]
check in this branch https://github.com/MindMatrix/AMP/pull/52387

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, @sunrao Sir, I have checked above security issue and basic functionality on the given branch ( https://pr-52387.dvl.amp.vg/login ) and its working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir,  I have checked above issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify this.

**Comment by prashantjadhav92** [comment]
Verified by the client.
