### ISSUE TITLE
SEC-5073 - IDOR allowing to unsubscribe other users from emails, /api/SetSubscription

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#148]
IDOR on /api/SetSubscription allowing to unsubscribe other users from emails

Steps to reproduce:
* Send the following request. Replace <SESSION>, <CSRF_TOKEN>, and <CONTACT_ID> with appropriate values. <CONTACT_ID> should be ID of contact from another organization:

curl -X POST https://partners.acronis.com/api/markDoneNotification -H "Content-Type: application/json" -b ".ASPXAUTH=<SESSION>" -H "X-Csrf-Token: <CSRF_TOKEN>" -d '{"id":<TODO_ID>,"contactid":<CONTACT_ID>}'

* Check that contact was unsubscribed

Fix: it must not be possible to change data of other organizations

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked the above security issue and the user is able to unsubscribe contacts of other organization's user using the steps mentioned above.

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, @sunrao sir, I have checked above security issue and basic functionality on the given branch ( https://pr-52387.dvl.amp.vg/) and It's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify this.

**Comment by prashantjadhav92** [comment]
Verified by the client.
