### ISSUE TITLE
SEC-5079 - XSS via image name and display name

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#149]
XSS via image name

Steps to Reproduce:
1. Visit this page https://partners.acronis.com/#gallery/banner/images
2. Upload any image
3. Change the image dispay name to this payload: xss" onmouseover="confirm(777)
4. When it is saved, move mouse over just created image and see JS executed
![1](https://user-images.githubusercontent.com/31324885/189748380-19efb9f2-0a53-43d5-9ee5-2876ab1ab7f5.png)

 5. The same issue exists for name field, XSS payload from which is executed on page https://partners.acronis.com/#setup/organization/gallery/image/<org_ID>. At the moment it is not possible anymore to set payload from step (3) in this field, however if this payload was saved before, payload would still execute on this page, e.g. on https://partners.acronis.com/#setup/organization/gallery/image/23/:
![2](https://user-images.githubusercontent.com/31324885/189748416-bf91bd01-0a2f-47d7-9bd4-bb7b94fc7804.png)

Fix: encode untrusted input according to the rendering context

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have checked above security issue and JS is getting executed by following above mentioned steps.
![image](https://user-images.githubusercontent.com/92088937/189860006-f8810947-1fad-4ebe-b50b-ff8b2ce8788d.png)

**Comment by shivmishra** [comment]
can you check on https://github.com/MindMatrix/AMP/pull/51734 branch, can you ask every tester to verify xss issue on  the mentioned PR.

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, I have checked above security issue on the given branch ( https://pr-51734.dvl.amp.vg/ ) JS not getting execute.
but if I click on sharing from three dots (more info) a image showing zero ( 0 ) on the modal.
![image](https://user-images.githubusercontent.com/92088937/190384642-1d2deab9-d3ce-47aa-b259-6218efe7777d.png)

**Comment by Vinayakvs1994** [comment]
@IshantRevclerx please test this after build in this branch https://github.com/MindMatrix/AMP/pull/51734

**Comment by shivmishra** [comment]
@IshantRevclerx plz check here https://github.com/MindMatrix/AMP/pull/52699

**Comment by IshantRevclerx** [comment]
@shivmishra sir, @sunrao sir, I have checked above security issue and basic functionality on the given branch ( https://pr-52699.dvl.amp.vg/ ) and It's working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis production and Its's working as expected now.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client to confirm.

**Comment by prashantjadhav92** [comment]
Client has confirmed the fix.
