### ISSUE TITLE
#1478752, #1478750, #1478749, #1478747, #1478743 XSS on user profile page (02/14/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#15]
Severity: Medium

Fields city, address, telephone, firstname, lastname are vulnerable to stored XSS on page /#user/profile/. 
Steps to reproduce:
Login under admin
Copy session cookie .ASPXAUTH and X-CSRF-Token values 
Go to /#setup/users/list
Copy ID of any user, e.g. <TEST_USER_ID>
Make the following request:
curl  <URL>/api/SaveUser -H “X-CSRF-Token: <CSRF_COOKIE_VALUE>” -b “.ASPXAUTH=<ASPXAUTH_COOKIE_VALUE>” -d '{"userid":<TEST_USER_ID>,"syncusername":null,"groups":[],"json":{"name":"test@test.com","email":"test@test.com","firstname":"testXSS\" onmouseover=\"alert(1)","lastname":"testXSS\" onmouseover=\"alert(2)","title":null,"portfolio":null,"photoid":null,"signature":null,"url":null,"blogurl":null,"twitter":null,"facebook":null,"linkedin":null,"youtubeurl":null,"bio":null,"signwhensendingemail":true,"address":”testXSS\" onmouseover=\"alert(4)”,"address2":null,"address3":null,"city":”testXSS\" onmouseover=\"alert(3)”,"state":null,"zipcode":null,"country":null,"telephone":”testXSS\" onmouseover=\"alert(5)”,"mobile2":null,"fax":null,"timezonename":null,"locale":null,"cookiepolicy":"1","language":"8","assetautosave":false,"f_10":false,"f_11":false,"f_12":false,"f_13":false,"f_15":false,"f_17":false,"personaoptionid":null},"partnerorganizationid":0,"contactid":0,"cfjson":{"f_10":false,"f_11":false,"f_12":false,"f_13":false,"f_15":false,"f_17":false}}'
Login under <TEST_USER_ID>
Go to /#user/profile/ and hover over the corresponding fields (city, phone number, first and last name and address and see JS executed
Fix requirement - encode untrusted input according to the rendering context. Make sure, that other fields are not vulnerable as well

**Comment by shaileshtayde** [comment]
Install - https://acronis2.sb.amp.vg/#user/profile/1647736355524
User - shailesh31@mailinator.com
JSON - 
`{"userid":2354,"syncusername":null,"groups":[],"json":{"name":"shailesh31@mailinator.com","email":"shailesh31@mailinator.com","firstname":"testXSS\" onmouseover=\"alert(1)","lastname":"testXSS\" onmouseover=\"alert(2)","title":null,"portfolio":null,"photoid":null,"signature":null,"url":null,"blogurl":null,"twitter":null,"facebook":null,"linkedin":null,"youtubeurl":null,"bio":null,"signwhensendingemail":true,"address":"testXSS\" onmouseover=\"alert(4)","address2":null,"address3":null,"city":"testXSS\" onmouseover=\"alert(3)","state":null,"zipcode":null,"country":null,"telephone":"testXSS\" onmouseover=\"alert(5)","mobile2":null,"fax":null,"timezonename":"Eastern Standard Time","locale":null,"cookiepolicy":"1","language":"8","assetautosave":false,"f_10":false,"f_11":false,"f_12":false,"f_13":false,"f_15":false,"f_17":false,"personaoptionid":null},"partnerorganizationid":0,"contactid":0,"cfjson":{"f_10":false,"f_11":false,"f_12":false,"f_13":false,"f_15":false,"f_17":false}}`

![image](https://user-images.githubusercontent.com/6465652/159143139-0643da0f-e235-4e68-a091-bb5c2ad1956d.png)

**Comment by NagmaKadiri** [comment]
@shaileshtayde PR - #48700 created for testing.

**Comment by PuneetRevclerx** [comment]
@shaileshtayde Sir, I have tested the above security issue on production and issue still exists:

![image](https://user-images.githubusercontent.com/102346181/178243869-d236bb16-1c71-4e45-a060-cfca1cffd710.png)

**Comment by PuneetRevclerx** [comment]
@Mahimapatil mam, @sunrao sir, I have checked above security issue on https://acronis2.sb.amp.vg/ and it's working as expected now.

**Comment by Mahimapatil** [comment]
@PuneetRevclerx PR for this https://github.com/MindMatrix/AMP/pull/52525

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
The fix has been verified.
