### ISSUE TITLE
SEC-5088 - IDOR to access organization images, /api/GetImagesForCurrentUser

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#150]
IDOR to access organization images, API endpoint /api/GetImagesForCurrentUser is vulnerable

Steps to Reproduce:
Send the following request. Replace <SESSION>, <CSRF_TOKEN>, and <ASSET_ID> with appropriate values. <ASSET_ID> should be ID of another organization (it looks like only images uploaded the following way are visible in this case: go to https://partners.acronis.com/#setup/users/list of some organization -> any user -> click on organization name -> choose Image Gallery and upload image):

curl -X POST https://partners.acronis.com/api/GetImagesForCurrentUser -H "Content-Type: application/json" -b ".ASPXAUTH=<SESSION>" -H "X-Csrf-Token: <CSRF_TOKEN>" -d '{"page":0,"pageSize":15,"sort":"createdon","ascending":false,"filters":[],"condition":false,"format":4,"startdate":"","enddate":"","folder":{"sort":["createdon","updatedon","filename"],"viewindex":-1,"name":"All Images"},"filterID":"0","type":5,"assetid":<ASSET_ID>,"isorganization":true}'
 
...
"name":"scrot_selection_Sep052022_163215xss+ onmouseover=+confirm(777).png","friendlyname": "scrot_selection_Sep052022_163215xss+%20onmouseover=+confirm(777).png", "escapedfilename":"scrot_selection_Sep052022_163215xss+%20onmouseover= +confirm(777).png","original":"[https://partners.acronis.com/img/bbou7q87bjy3g/thumb-scrot_selection_Sep052022_163215xss__onmouseover__confirm_777_.png","downloadurl":](https://partners.acronis.com/img/bbou7q87bjy3g/thumb-scrot_selection_Sep052022_163215xss__onmouseover__confirm_777_.png%22,%22downloadurl%22:)
...
See that links to images from another organization are accessible

Fix: it must not be possible to access data of other organizations

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have checked above security issue and user is able to access the images of other organization's user by following the above mentioned steps.

**Comment by shivmishra** [comment]
check in this branch https://github.com/MindMatrix/AMP/pull/52387

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, @sunrao Sir, I have checked above security issue and basic functionality on the given branch ( https://pr-52387.dvl.amp.vg ) and It's working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir,  I have checked above issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
Verified by the client.
