### ISSUE TITLE
SEC-5091 - XSS on /#setup/organization/overview/<org_ID> page

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#151]
XSS on /#setup/organization/overview/<org_ID> page via Website Url parameter

Steps to Reproduce
* Visit this page https://partners.acronis.com/#setup/users/list
* Click on any user
* Click on the organization name
* Chose the info tab to edit the organization
* In Website URL field set the following value: [https://www.WebsiteUrl.live'](https://www.websiteurl.live%27/) onmouseover='confirm(416)
* Now visit this endpoint /#setup/organization/overview/<org_ID> and move mouse over the website URL
* See XSS executed

![1](https://user-images.githubusercontent.com/31324885/189750311-8501d771-d52c-4510-8efb-ee48abdef94d.png)

Fix: encode untrusted input according to the rendering context. https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked the above security issue and JS is getting executed by following the above-mentioned steps.

![image](https://user-images.githubusercontent.com/102346181/189859401-8a0d54f6-2540-4e1d-8873-7250c87487ea.png)

**Comment by shivmishra** [comment]
@Vinayakvs1994 plz fix on priority

**Comment by Vinayakvs1994** [comment]
@sunrao sir this issue is done in this https://github.com/MindMatrix/AMP/pull/52401
please assign this for this testing

**Comment by PuneetRevclerx** [comment]
@Vinayakvs1994, @shivmishra sir, I have checked above security issue on the given branch (https://pr-52401.dvl.amp.vg/) and JS is not getting executed.
But, I am not able to paste the copied text to any of the input fields using (Ctrl + V) or by right click and using the paste option.

**Comment by shivmishra** [comment]
@Vinayakvs1994 update main

**Comment by Vinayakvs1994** [comment]
@PuneetRevclerx Please check after branch is build.
@shivmishra sir done

**Comment by PuneetRevclerx** [comment]
@shivmishra sir @sunrao sir, I have checked above security issue and basic functionality on the given branch (https://pr-52401.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify this.

**Comment by prashantjadhav92** [comment]
Verified by the client.
