### ISSUE TITLE
SEC-5092 - IDOR via /manage/case-history/2/<case_id> API endpoint

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#152]
IDOR via /manage/case-history/2/<case_id> API endpoint

Steps to reproduce:
Open in browser (set <CASE_ID> to ID of a case from any other organization):
view-source:https://partners.acronis.com/manage/case-history/2/<CASE_ID>
Find pageData on page and see case history

Example: view-source:https://partners.acronis.com/manage/case-history/2/60782
![scrot_selection_Sep122022_211821](https://user-images.githubusercontent.com/31324885/189750655-be4e4936-00f0-4dd4-a134-9c69037ba73d.png)

Fix: it must not be possible to access data of another organizations

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked the above security issue on https://partners.acronis.com/ and if a user is a partner admin then he can see the case details of other organizations' users.

**Comment by HareshKedar** [comment]
@PuneetRevclerx this got fixed in recent update on prod. couple of hours ago.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have verified the above issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
Assigned to client for confirmation.

**Comment by prashantjadhav92** [comment]
Verified by the client.
