### ISSUE TITLE
SEC-5131 - Spellcheck not disabled for login and password fields

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#154]
Enhanced Spellcheck Feature in Chrome & Edge browser sends form field values to Google & Microsoft. This includes login and password fields (for password if "show password" button was clicked by the user). It is required to disable spellcheck for corresponding fields to avoid sensitive information leakage.

Fix: Add attribute spellcheck=false to login and password fields (this includes password reset / change fields) to disable spell check

References:
https://www.otto-js.com/news/article/chrome-and-edge-enhanced-spellcheck-features-expose-pii-even-your-passwords

![scrot_selection_Sep192022_191059](https://user-images.githubusercontent.com/31324885/191106310-17fd0b09-7351-464e-a674-61bc8587a014.png)

**Comment by shaileshtayde** [comment]
![image](https://user-images.githubusercontent.com/6465652/191225815-79501954-2695-4835-8434-8bca380f31c4.png)

**Comment by prashantjadhav92** [comment]
@shaileshtayde I have asked the client to verify the same.

**Comment by prashantjadhav92** [comment]
@HareshKedar @shaileshtayde the client has mentioned that this is not present on the password change field in the user's profile - Confirm new password field (where there is a button "show password" present) does not have a spellcheck attribute. The same for the password reset page

**Comment by HareshKedar** [comment]
@prashantjadhav92 This is done on sandbox. Kindly verify.

**Comment by PuneetRevclerx** [comment]
@HareshKedar sir, @sunrao sir, I have checked above issue on Acronis Sandbox and it's working as expected now.

@HareshKedar sir, Kindly update it on Acronis Production.

**Comment by PuneetRevclerx** [comment]
As per our discussion, assigning it back to Haresh sir.

**Comment by HareshKedar** [comment]
@PuneetRevclerx This is fixed on sandbox now.

**Comment by PuneetRevclerx** [comment]
@HareshKedar sir, @sunrao sir, I have checked above issue on Acronis Sandbox and it's working as expected now.

@HareshKedar sir,  Kindly update it on Acronis Production.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
The client has verified the fix.
