### ISSUE TITLE
SEC-5108 - Information about all organizations accessible via /api/GetAllOrganizations

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#155]
Information about all organizations accessible via /api/GetAllOrganizations.

Steps to reproduce:

Make the following request. Set proper <SESSION> and <CSRF_TOKEN> values
1. curl -X POST https://partners.acronis.com/api/GetAllOrganizations -H "Content-Type: application/json" -b "jwt=<SESSION>" -H "X-Csrf-Token: <CSRF_TOKEN>" -d '{}' -s

2. {"result":{"schema":{"id":"int64","name":"string","address1":"string","address2":"string","address3":"string","city": "string","state":"string","zipcode":"string","country":"string","telephone":"string","fax":"string","url": "string","photoid":"int64","email":"string","linkedin":"string","facebook":"string","twitter":"string", "color1":"string","color2":"string","color3":"string","color4":"string","createdon":"datetime", "updatedon":"datetime","currency":"string","photoid1":"int64","photoid2":"int64","photoid3": "int64","photoid4":"int64","photoid5":"int64","photoid6":"int64","areaserved":"string", "revenuegoals":"string","externalid":"string","signature":"string","tos":"string","cookiepolicy": "byte","ismasteragent":"bool","masteragentprimarycontact":"int64","masteragentid":"int64", "publicid":"string","googlereviewlink":"string","initialonboarding":"bool","trainingcompleted": "bool","certificationcompleted":"bool","marketingenabled":"bool","salesenabled":"bool", "businessplanning":"bool","issupplier":"bool","suppliertype":"byte"},"item":[{"id":31988,"name":"!delete","address1":null,"address2":null,"address3":null,"city":null, "state":null,"zipcode":null,"country":null,"telephone":"","fax":null,"url":...

Fix: It must not be possible to access data of other organizations

**Comment by shivmishra** [comment]
https://github.com/MindMatrix/AMP/pull/52511
Please check here

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, @sunrao sir, I have checked above security issue on the given branch (https://pr-52511.dvl.amp.vg) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
Asked the client to verify.

**Comment by prashantjadhav92** [comment]
Asked the client to verify.

**Comment by prashantjadhav92** [comment]
Verified by the client.
