### ISSUE TITLE
SEC-5107 - It is possible to access information about other users using /api/GetAllUsers endpoint

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#156]
It is possible to access information about other users using /api/GetAllUsers endpoint

Steps to reproduce:

Make the following request, set proper <SESSION> and <CSRF_TOKEN> values
curl -X POST https://partners.acronis.com/api/GetAllUsers -H "Content-Type: application/json" -b "jwt=<SESSION>" -H "X-Csrf-Token: <CSRF_TOKEN>" -d '{}' -s

{"result":{"schema":{"id":"int64","photoid":"int64","name":"string","email":"string","firstname":"string","lastname": "string","country":"string","telephone":"string","mobile":"string","mobile2":"string","islockedout": "bool","issiteadmin":"bool","issuperadmin":"bool","totallogins":"int32","lastlogindate":"datetime", "lastdistribution":"int64","createdon":"datetime","updatedon":"datetime","companyname":"string" ,"cansendsms":"bool","latitude":"float","longitude":"float","externalid":"string","companyprofile": "string","organizationid":"int64","tosaccepted":"bool","tosacceptedon":"datetime","cookiepolicy": "byte","language":"int32","publicid":"string","lastacceptedtos":"datetime","certifieduser":"bool", "passwordresetrequestdate":"datetime","source":"byte"},"item":
...
"mobile2":"null","islockedout":false,"issiteadmin":false,"issuperadmin":false,"totallogins":0, "lastlogindate":"1/1/1800 12:00:00 AM UTC","lastdistribution":64640,"createdon": "5/26/2021 5:44:18 PM UTC","updatedon":"1/23/2022 11:53:30 AM UTC","companyname":null,"cansendsms":null,"latitude":null,"longitude":null,"externalid": "0035000000UxiamAAB","companyprofile":null,"organizationid":8962,"tosaccepted": false,"tosacceptedon":null,"cookiepolicy":1,"language":8,"publicid": "60ae88f29796bf087c0b9f99","lastacceptedtos":null,"certifieduser": false,"passwordresetrequestdate":null,"source":null,"friendlyname":"64915", "selected":"0","publickey":"cl0m5k37pw5o1","t
Fix: It must not be possible to access data about users from other organizations

**Comment by shivmishra** [comment]
please check here
https://github.com/MindMatrix/AMP/pull/52511

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, @sunrao Sir, I have checked above security issue on the given branch ( https://pr-52511.dvl.amp.vg/ ) and It's working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
Asked the client to verify.

**Comment by prashantjadhav92** [comment]
Verified by the client.
