### ISSUE TITLE
SEC-4460 Stored-XSS in filters input [videos gallery]

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#158]
1. Go to edit an video https://partners.acronis.com/#gallery/videos
2. Intercept the request to the endpoint /api/savevideo and 
3. Set [filters] parameter: XSS\" onclick=\"alert(164)
4. Forward the Request and go back to videos gallery https://partners.acronis.com/#gallery/videos
5. A new filter is created. It executes JS if it's clicked

**Comment by sunrao** [comment]
@IshantRevclerx / @PuneetRevclerx Pl. check this on the XSS branch of @shivmishra

**Comment by shivmishra** [comment]
yes plz check on mentioned branch https://github.com/MindMatrix/AMP/pull/52281

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, I have checked the above issue on the given branch (https://pr-52281.dvl.amp.vg/) and "Edit" button is not showing on the video and also thumbnail is not loading. On main "Edit" button is visible along with the thumbnail of the video.

On main:
![image](https://user-images.githubusercontent.com/102346181/191468439-a6f7ca08-b6e5-4ab0-b21f-97d214fd4bb7.png)

On Branch:
![image](https://user-images.githubusercontent.com/102346181/191469074-ec8109f5-80d0-4cdf-9e01-7aa10977304b.png)

**Comment by shivmishra** [comment]
@PuneetRevclerx i update the branch from main, so please check again. if still didnt work then could be some video setting issue on main and branch and in such case plz check for filter here.

if you still want to sure check on any other 3rd branch.

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, @sunrao sir, I have checked above security issue and basic functionality on the given branch (https://pr-52281.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify the fix.

**Comment by prashantjadhav92** [comment]
Fix has been verified by the client.
