### ISSUE TITLE
#1429940 Improper access control allows to modify level/plan of the partner program, (/api/SaveOrganization)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#159]
It is possible to change organization level/plan using request to /api/SaveOrganization. In fields f_34, f_36, f_35, f_37 required level might be specified, e.g. "f_34":"Service provider","f_36":"Authorized","f_35":"Reseller","f_37":"Platinum".
Afterwards, it might be verified on /#partnerprogram page, that level/plan was changed.
 
As per Acronis, even if the user has organization edit access, it should not be able to update the level/plan of their organization.

**Comment by shaileshtayde** [comment]
@prashantjadhav92 @sunrao We don't have a special permission to restrict particular fields of an organization. This is completely driven on organization edit fields only. 
@shivmishra  Can we set the visibility or accessibility of these Organization fields so only Super Admin users can edit resp. fields?

**Comment by shivmishra** [comment]
right now we cannot fix this and after organization layout enhancement we would be able to hide the tab i guess.

@sunrao is that correct?

**Comment by sunrao** [comment]
@shaileshtayde The tabs can be hidden and all the fields in the tab will be hidden

**Comment by sunrao** [comment]
@shaileshtayde If visible for the user it can be updated from the front end

**Comment by shivmishra** [comment]
@shaileshtayde yes if user add field and value in json it will be updated

**Comment by shaileshtayde** [comment]
@sunrao @prashantjadhav92 This is our default functionality. Please have this discussed with @cphillips83 + Vedonia as it may require a new implementation of accessibility per field and it will be complex one (This was discussed with @shivmishra already)

**Comment by shaileshtayde** [comment]
@sunrao Assigning this to @shivmishra as he's working on this  one. @cphillips83 fyi.
@PuneetRevclerx @IshantRevclerx @prashantjadhav92 This would need investigation on Shiv's end, hence consider this is work in progress.

**Comment by prashantjadhav92** [comment]
Thank you for the update @shaileshtayde.

**Comment by prashantjadhav92** [comment]
@shivmishra, can super admins update these fields?

**Comment by shivmishra** [comment]
no

**Comment by sunrao** [comment]
@shivmishra The fields can be edited and saved for users who can view the fields i.e. based on the tab view of the fieldset

**Comment by shivmishra** [comment]
no this is not related to tab. protected means protected for system. Please talk to @cphillips83 and get his approval

**Comment by sunrao** [comment]
@shivmishra Chris has mentioned that 
If you want to disable what is allowed to be updatable, you change this setting, then if you still need to modify it, then you have to take it as an additional param and manually set it in the API.

Hence in the API if there is visibility for the User it can be updated

**Comment by shivmishra** [comment]
![image](https://user-images.githubusercontent.com/6465643/197002565-85fdd7aa-2764-4729-8586-c370bb5ac903.png)

**Comment by sunrao** [comment]
@cphillips83 @shivmishra Following is the requirement
Organization custom tabs can be made visible to specific users from the show/hide settings
![image](https://user-images.githubusercontent.com/6465639/197748635-c30829d0-1fe0-46d7-9263-1a3df4f0b94d.png)

![image](https://user-images.githubusercontent.com/6465639/197748655-adf224aa-563d-4895-91b5-662c297f77e6.png)

From the front end, since the user can see only those tabs and fields in them that are made visible to the user, he can edit only these fields. In the API we expose all the fields and the requirement is for the user the API should also allow to modify and save those fields that are visible for the user

**Comment by shivmishra** [comment]
@IshantRevclerx @PuneetRevclerx plz verify on this PR

**Comment by sunrao** [comment]
@IshantRevclerx Pl. check this

**Comment by IshantRevclerx** [comment]
@shivmishra sir, @sunrao sir, I have checked above security issue on the given branch (  https://pr-53481.dvl.amp.vg ) and now if custom filed not visible to user then he is not able to edit the values of those field.

**Comment by sunrao** [comment]
Super job

**Comment by sunrao** [comment]
@IshantRevclerx Pl. demonstrate to @prashantjadhav92 what has been fixed, basically if user doesn't have access to the tab the user cannot change the values even from API for the fields from the tab

**Comment by prashantjadhav92** [comment]
I have asked the client to verify the fix.

**Comment by prashantjadhav92** [comment]
Client has verified the fix.
