### ISSUE TITLE
#1479528 IDOR allows to delete email blast from other organizations, /api/deleteemails (02/14/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#16]
Severity: Medium

POST request to /api/deleteemails ({"ids":[<EMAIL_BLAST_ID>],"cstatus":1}) contains id of the email blast. It is possible to specify <EMAIL_BLAST_ID> created in another organization and delete it

**Comment by shaileshtayde** [comment]
@shivmishra Can you please confirm if this API has the generalized permission check instead of specific email one?

**Comment by shivmishra** [comment]
@sunrao this is fixed here ask someone to test 
https://github.com/MindMatrix/AMP/pull/48276

**Comment by YogeshRevclerx** [comment]
@shivmishra I have tested this on the branch. It has been fixed and One user can not able to delete an email of another organization with an Email blast id.

**Comment by shivmishra** [comment]
@YogeshRevclerx if its working then you have to close the issue and signoff in the PR

**Comment by prashantjadhav92** [comment]
@shivmishra @YogeshRevclerx is this fix released?

Please mark the issues closed only when the fix is released else it will cause confusion and I won't know when to send an update to the clients.

**Comment by shivmishra** [comment]
its not released. will take care from next time

**Comment by YogeshRevclerx** [comment]
@shivmishra Sir i am still able to delete the email from another organization. 
Email Blast id:- 6624
User:- Sharmayug75

**Comment by shivmishra** [comment]
should be fixed now

**Comment by YogeshRevclerx** [comment]
@shivmishra It has been fixed.

![image](https://user-images.githubusercontent.com/92095999/161569652-e29a0f9d-e185-4a19-979c-4fcb4d261a9c.png)

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have checked above mentioned Security issue on production and its working fine.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client to confirm.

**Comment by prashantjadhav92** [comment]
Confirmed by the client.
