### ISSUE TITLE
XSS: JS is getting executed on export status page.

### ISSUE THREAD

**Issue by PuneetRevclerx** [MindMatrix/SecurityTracker#160]
URL: https://main.dvl.amp.vg/#connections/export/status

STR:
1. Export Contact, opportunity or pdf report.
2. Repeat the process and in API change the name of the export file to (New "onmouseover=confirm(1)).
3. Now, go to Connection>> Export Status.
4. Hover the mouse over the export file name.

Actual Result: JS will execute by hovering the mouse over the export file name.

**Contact**:
![image](https://user-images.githubusercontent.com/102346181/192696164-e12613d3-a476-4f64-8020-ad5275ab23cc.png)

**Opportunity**:
![image](https://user-images.githubusercontent.com/102346181/192696245-de749c95-e2d5-4e7a-ad62-35327505d893.png)

**PDF Report**:
![image](https://user-images.githubusercontent.com/102346181/192696329-e2e3e175-7fac-4827-a1f0-373538db2e6b.png)

Expected Result: JS should not get executed.

**Comment by shaileshtayde** [comment]
@PuneetRevclerx This should be fixed in @shivmishra sir's branch where ke fixed all XSS issues in dot-template. Can you please have this validated there.

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, PR- 51734, where all the XSS issues were fixed, was not released and is closed now. Also, Sunil sir told us to assign all the issues fixed in that PR to the respective developers.

**Comment by sunrao** [comment]
@Mahimapatil Get the page done in Razor with all permission checks

**Comment by Mahimapatil** [comment]
@sunrao Done in https://pr-52769.dvl.amp.vg/

**Comment by PuneetRevclerx** [comment]
URL: https://pr-52769.dvl.amp.vg/#connections/export/status

When we first go to the above URL, contact, and user both tabs show selected and the user cannot switch between these two. The user has to click on any other tab then he can move back to the contact or user tab.

![image](https://user-images.githubusercontent.com/102346181/192940777-9b457213-7f66-407d-8751-cd09832ba19d.png)

**Comment by Mahimapatil** [comment]
@PuneetRevclerx Done

**Comment by PuneetRevclerx** [comment]
@Mahimapatil mam, @sunrao sir, I have checked above security issue on the given branch (https://pr-52769.dvl.amp.vg/) and it's working as expected now.
