### ISSUE TITLE
XSS : JS is getting executed on company smart list name 

### ISSUE THREAD

**Issue by IshantRevclerx** [MindMatrix/SecurityTracker#161]
URL : https://main.dvl.amp.vg/#setup/companysmartlists

STR : 
1) Go to above url>>> Click on create button
2) Enter  [Test" onmouseover="confirm(164) ] in the name field 
3) Fill the requireds filleds and click on finish button.
4) Now hover the mouseover the newly created list

Actual Result : JS is getting executed on company smart list name 
![image](https://user-images.githubusercontent.com/92088937/192698121-9042b1ab-3e94-4370-ad54-f882e4f1f95a.png)

Expected Result : JS should not get execute.

**Comment by sabhareeraj** [comment]
@sunrao sir, Issue fixed in above PR. Kindly assign tester.

**Comment by IshantRevclerx** [comment]
@sabhareeraj @sunrao sir, I have checked above security issue and It's working as expected.

**Comment by IshantRevclerx** [comment]
@sunrao sir, I have checked above security issue and basic functionality, Its working as expected now.
