### ISSUE TITLE
SEC-4417 Possible to bypass file access restrictions

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#162]
It is possible to bypass file access restrictions by modifying file URL. For example, changing /file/ to /img/ in the following URL will allow to obtain access to the file:
https://partners.acronis.com/file/cchj6znwbae5y/LicenseCertificate-SOCH586561.pdf

->

https://partners.acronis.com/img/cchj6znwbae5y/LicenseCertificate-SOCH586561.pdf

Fix: It should not be possible to bypass file access restrictions

Note: Also, test this on firefox browser.

**Comment by shivmishra** [comment]
@sunrao @IshantRevclerx should be fixed here
https://github.com/MindMatrix/AMP/pull/53058

**Comment by shivmishra** [comment]
@IshantRevclerx should be fixed after branch build

**Comment by shivmishra** [comment]
@IshantRevclerx this document uploaded from case records

**Comment by IshantRevclerx** [comment]
@shivmishra sir, I have checked on main and mm live but we can not reproduce it.
kindly let us know,  how we can reproduce this issue, so that we can reproduce on the branch.

**Comment by shivmishra** [comment]
once i will fix at my end then will try to reproduce

**Comment by shivmishra** [comment]
@IshantRevclerx you can check now

**Comment by prashantjadhav92** [comment]
@IshantRevclerx was this verified?

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, PR- 53058 of this ticket has not gone to the Acronis production yet. Firstly we need to tested on Acronis Sand Box and for that we need to merged it on Acronis Sand box.

**Comment by IshantRevclerx** [comment]
@sunrao sir and @shivmishra sir, I have checked above issue on given branch ( https://pr-54304.dvl.amp.vg/ ) and Its working as expected now.

**Comment by IshantRevclerx** [comment]
@shivmishra sir and @sunrao sir, I have checked above ticket on Acronis Production, Follow the above mentioned steps 
for the PDF file showing below message.
![image](https://user-images.githubusercontent.com/92088937/206962191-a87d2cf4-12c9-4b31-a574-7c1b6a92e6ae.png)

for the text file still reproduce the above issue.

Note : Its working fine for dvl and mm live.

**Comment by shivmishra** [comment]
if in mm working then in acronis should also work if code updated. 
Please talk to @shaileshtayde

**Comment by shaileshtayde** [comment]
@shivmishra @IshantRevclerx let's have a call on this one at 3 today

**Comment by IshantRevclerx** [comment]
@shaileshtayde sir Ok.

**Comment by IshantRevclerx** [comment]
@shaileshtayde sir, I have checked above security issue on Acronis Sb and its working as expected

**Comment by prashantjadhav92** [comment]
@shaileshtayde as per @IshantRevclerx's last update this is working fine on the sandbox. Can you please confirm if this is released on production?

**Comment by shivmishra** [comment]
https://github.com/MindMatrix/AMP/pull/57081

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir I have checked above security issue on Acronis Production and It's working as expected now.

**Comment by prashantjadhav92** [comment]
The client has confirmed this to be fixed.
