### ISSUE TITLE
Open Redirect Vulnerability

### ISSUE THREAD

**Issue by shaileshtayde** [MindMatrix/SecurityTracker#167]
Open Redirection is by default supported by our application but as a security standard, secured application shouldn't allow to application to redirect to external url (e.g. google/hotmail/etc.)

URL - https://main.dvl.amp.vg/login?returnurl=aHR0cHM6Ly9hYmMuY29t
Notes -
An open redirect is an application that takes a parameter and redirects a user to the parameter value without any validation. This vulnerability is used in phishing attacks to get users to visit malicious sites without realizing it.

Observation:
It is observed that the application is not validating "ReturnUrl" request parameter, due to that the application is vulnerable to open redirect vulnerability.

Steps:
1. Visit the url and login in application using provided credentials.
2. Observe the response in browser.
3. Encode the url "https://abc.com" in base64 as shown in below screenshot.
4. Open new tab and paste the url "https://mindmatrix.sb.amp.vg/login?returnurl=aHR0cHM6Ly9hYmMuY29t" in browser as shown in screenshot.
5. Observe the response in browser showing content of "abc.com"

In order to tackle that, we've made a provision (config.xml) where we can turn this feature on/off.  
<disableopenredirect>true/false</disableopenredirect>

**Comment by shaileshtayde** [comment]
@IshantRevclerx @PuneetRevclerx have this tested in this branch;
https://github.com/MindMatrix/AMP/pull/55369 > http://pr-55369.dvl.amp.vg/

**Comment by IshantRevclerx** [comment]
@shaileshtayde sir, I have checked above issue on given PR(https://pr-55369.dvl.amp.vg/) and It's working as expected now.

**Comment by IshantRevclerx** [comment]
@shaileshtayde sir, and @sunrao sir I have checked above security issue on mm live and Its working as expected now.
