### ISSUE TITLE
HCL Application Security 1

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#168]
Enable CSP headers via your webserver configuration.
hcltechsw.com
https://partners.hcltechsw.com/

**Comment by shaileshtayde** [comment]
Added resp. header in hcl sandbox; Waiting on @cphillips83 feedback for prod push
 ```
 <additional_headers>
    <x_frame_options>ALLOW-FROM hcltechsw.com https://partners.hcltechsw.com</x_frame_options>
  </additional_headers>
```

**Comment by shaileshtayde** [comment]
Option has been discussed with @cphillips83. Waiting on feedback on the same.

**Comment by shaileshtayde** [comment]
@prashantjadhav92 @IshantRevclerx @PuneetRevclerx this has been enabled on [sandbox ](https://hcl.sb.amp.vg/). This has been sent to @apmohnot @cphillips83 to add the same in production.

**Comment by prashantjadhav92** [comment]
@shaileshtayde is this resolved on HCL production?

**Comment by shaileshtayde** [comment]
@prashantjadhav92  yes, its on production, kindly confirm the same as I mentioned in above attached image

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on HCL production and option is added in the request header.
![image](https://user-images.githubusercontent.com/92088937/225323266-d0156cea-5b69-4f8c-978e-807edc99efb9.png)

**Comment by prashantjadhav92** [comment]
Thank you for confirming @IshantRevclerx. I will ask the client to verify the same.
