### ISSUE TITLE
HCL Application Security 2

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#169]
Add one of the following headers, using the 'DENY' or 'ALLOW-FROM' directive, to responses from this website: X-Frame-Options: DENY' X-Frame-Options: ALLOW-FROM https://example.com/'

hcltechsw.com
https://partners.hcltechsw.com/
Header missing

**Comment by shaileshtayde** [comment]
Added resp. header in [hcl sandbox](https://hcl.sb.amp.vg/); Waiting on @cphillips83 feedback for prod push
 ```
 <additional_headers>
    <x_frame_options>ALLOW-FROM hcltechsw.com https://partners.hcltechsw.com</x_frame_options>
  </additional_headers>
```

**Comment by shaileshtayde** [comment]
This will be on production in upcoming release i.e. 9th March 20023

**Comment by prashantjadhav92** [comment]
@shaileshtayde, is this resolved on HCL production?

**Comment by shaileshtayde** [comment]
Yes, kindly check as mentioned in the screenshot attached in the issue.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked the above security issue on HCL production, and option is added in the request header.

![image](https://user-images.githubusercontent.com/102346181/225322597-9fd7ed07-ba6b-4751-86ca-1369ea339274.png)

**Comment by prashantjadhav92** [comment]
Thank you for confirming @IshantRevclerx
