### ISSUE TITLE
SEC-5735 IDOR to delete partners customers in different organization [ /api/DeleteUsers]

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#170]
1.Visit this page with (A) account https://partners.acronis.com/#setup/users/list
2. Try to delete any user
3. In the Burp Suite intercept the request and change the JWT token with (B) account in different org.
4. Now send the request.
5. Now back to (A) account and you will see the account is deleted.

Fix Requirements:
* It must not be possible to delete users from other organizations

**Comment by prashantjadhav92** [comment]
@shaileshtayde @IshantRevclerx @PuneetRevclerx this issue was resolved in the past but not it is reproducible again.

**Comment by shaileshtayde** [comment]
@prashantjadhav92 Did you verify the permission as @shivmishra mentioned in an email?

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above-mentioned security issue on Acronis production but it's not getting reproduced at my end. Kindly provide user details and screen recording if possible so that we can verify it at our end.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx user is adoronina@acronis.net
This user has User = Delete, Organization profile = edit and Organization users = edit access.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I followed the same steps mentioned above and used jwt token of the user that you provided but still the issue is not getting reproduced.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx I have asked the client to check this again on their end.

**Comment by prashantjadhav92** [comment]
I will close this case since the issue is not reproducible anymore.

**Comment by prashantjadhav92** [comment]
@shaileshtayde @shivmishra @PuneetRevclerx, I received an update from Acronis that they are not able to reproduce this issue anymore on their end. But they have shared the attached video that confirms it was reproducible when they reported the issue recently so was there anything changed on our end that fixed the problem?

I need to share the details with them else they won't allow us to close the case. 

https://user-images.githubusercontent.com/31324885/224325087-f85ade59-6ef0-4b52-ad02-74946f1153d9.mp4

**Comment by shaileshtayde** [comment]
@prashantjadhav92 This must be because of permission updated. @shivmishra can you please check .

**Comment by shivmishra** [comment]
i guess i explain to @prashantjadhav92 on slack
