### ISSUE TITLE
Vartopia - Missing script subresource integrity check

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#174]
The website has referenced 3rd party scripts without setting the integrity check attributes. Sample includes but is not limited to:
 
https://cache.amp.vg/partners.globalrelay.com/bundles/7c115111ffeb4469d07adbfcdbfb2123ff8528fd/en/login.js

https://cache.amp.vg/partners.globalrelay.com/bundles/2fe41f966d32b41d0f50d0ef5da1e1e79565916f/en/login.js

https://www.google.com/recaptcha/api.js
 
Refer to https://www.w3.org/TR/SRI/ for more details.

**Comment by shaileshtayde** [comment]
@prashantjadhav92 @IshantRevclerx @PuneetRevclerx This is scheduled for upcoming release i.e. 16th MAR

**Comment by prashantjadhav92** [comment]
@shaileshtayde can you please share the latest update on this security point?

**Comment by IshantRevclerx** [comment]
@shaileshtayde sir , @sunrao sir I have checked above security issue on the given PR-59387 and SandBox on Vartopia. Its working as expected.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, above security issue on which Production Insatll we need to verify?

**Comment by prashantjadhav92** [comment]
@IshantRevclerx the https://partners.globalrelay.com/login url is working now. Please confirm if this security item is resolved.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on mentioned URL : https://partners.globalrelay.com/ and Missing script subresource integrity check is added.
![image](https://github.com/MindMatrix/SecurityTracker/assets/92088937/135068e4-436b-4fa2-96a3-531832a510b1)

**Comment by prashantjadhav92** [comment]
Thank you for confirming.
