### ISSUE TITLE
Vartopia - Missing X-Frame-Options and Content-Security-Policy security headers

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#175]
Detected on:
https://partners.globalrelay.com/login
 
Refer to the following documents for technical details:

https://www.ietf.org/rfc/rfc7034.txt

https://www.w3.org/TR/CSP3/

https://owasp.org/www-community/attacks/Clickjacking

**Comment by prashantjadhav92** [comment]
@IshantRevclerx can you please confirm if this is fixed?

**Comment by shaileshtayde** [comment]
@prashantjadhav92 @IshantRevclerx @PuneetRevclerx This is scheduled for upcoming release i.e. 16th MAR

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir above mentioned URL : https://partners.globalrelay.com/login is not working. 
Where we can verify this issue?

**Comment by prashantjadhav92** [comment]
@IshantRevclerx the https://partners.globalrelay.com/login url is working now. Please confirm if this security item is resolved.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir I have checked above security issue on mentioned URL (https://partners.globalrelay.com/login) and X-Frame-Options and Content-Security-Policy security added in the request header.
![image](https://github.com/MindMatrix/SecurityTracker/assets/92088937/9280e65f-1762-4439-b735-cf72cc2908f6)

**Comment by prashantjadhav92** [comment]
Thank you for confirming.
