### ISSUE TITLE
#1479573 Stored XSS on /#connections/contacts/filters/<CONTACT_ID> page (02/14/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#18]
Severity: Medium

 Stored XSS on /#connections/contacts/filters/<CONTACT_ID> page via filter name. Steps to reproduce:
Login and go to /#connections/contacts
Copy <CONTACT_ID> of any contact
Make request to /api/GetOrAddFilterForContact with filter parameter set to the following: qwerty\" onmouseover=\"confirm(123) and contactid set to <CONTACT_ID>
Open /#connections/contacts/filters/<CONTACT_ID> and hover over the filter
See JS executed

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have Checked above mentioned issue and after following the mentioned steps, JS is getting Executed.

![Contact-ID-Main](https://user-images.githubusercontent.com/92088937/176881771-4fff5577-dbb5-4fe8-b6e2-c87a1d122ea8.png)

**Comment by MeghanaThakekar** [comment]
please check in pr https://github.com/MindMatrix/AMP/pull/52281

**Comment by IshantRevclerx** [comment]
@MeghanaThakekar mam, @sunrao Sir, I have checked above security issue and basic functionality on the given branch ( https://pr-52281.dvl.amp.vg/ ) and It's working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify the fix.

**Comment by prashantjadhav92** [comment]
The fix has been verified.
