### ISSUE TITLE
[SEC-6604] IDOR in vendor setting

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#188]
Steps to reproduce

1. Using account A, go to Vendor Setting (https://partners.acronis.com/#setup/vendorsetting) and create a new vendor.

2. Using account B, go to Vendor Setting (https://partners.acronis.com/#setup/vendorsetting), see the newly created vendor in UI. If you check API response, you will also see FTP password in plaintext.

Expected results
Vendors are bound to the tenant they were created in and thus are not visible to other tenants.

Actual results
Vendors are visible to all tenants.

**Comment by IshantRevclerx** [comment]
@shaileshtayde sir I have checked above mentioned issue and Its reproduced on main (https://main.dvl.amp.vg/#setup/vendorsetting).

**Comment by shivmishra** [comment]
@prashantjadhav92 @IshantRevclerx @sunrao @shaileshtayde  this is company wise that's why one user's vendors showing in diff user's account. if this need to be corrected then use case should be discussed and documented.

After we know use cases we change of encrypted password.

**Comment by shaileshtayde** [comment]
@sunrao can you please reply to @shivmishra's comment

**Comment by prashantjadhav92** [comment]
@sunrao @shivmishra I have informed the client. I will get back once I receive their feedback.

**Comment by shaileshtayde** [comment]
@prashantjadhav92 Did you hear it from client?

**Comment by prashantjadhav92** [comment]
@shaileshtayde I will close this ticket.
