### ISSUE TITLE
#1479573 It is possible to see filter names created by other users (in other organizations), /public/search.ashx?q=test (02/14/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#19]
Is it supposed behavior that using /public/search.ashx?q=<FILTER_NAME_OR_ITS_PART> it is possible to see what filters are there on the platform (including those created in other organizations)?

**Comment by shaileshtayde** [comment]
@prashantjadhav92 filters that are created can be seen by all users. This is the part of default functionality to avoid filter duplication. You can confirm with @cphillips83 @sunrao
