### ISSUE TITLE
#1417610 XSS via image alt name

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#2]
login and upload any image in /#gallery/banner/images 
set alt name to the XSS payload, "xss onmouseover='alert("stored xss via image alt attribute")'"
set this image as logo in company profile (/#user/profile/)
upload any video on /#gallery/videos 
click Preview the video, move mouse over the company logo and see XSS executed

**Comment by PuneetRevclerx** [comment]
@shaileshtayde Sir, I have checked the above mentioned issue:
In "/api/RenameFile", set the display name as ("\"onmouseover=alert(1)//test.jpg") and on hovering the image JS will execute in "/#gallery/banner/images" as well as in "/#user/profile/" while trying to add that image as the company logo.

![image](https://user-images.githubusercontent.com/102346181/177173431-737ba3c4-0ba4-4c20-8cdb-e6ceed80e42f.png)

User: puneet security (Normal User)
Company: Automation Testers

**Comment by shivmishra** [comment]
https://github.com/MindMatrix/AMP/pull/51707
check here

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, @sunrao sir, I have checked the above security issue and basic functionality on the given branch (https://pr-51707.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis production and it's working as expected now.
