### ISSUE TITLE
#1474935 IDORS allows to see attachments to support tickets from other organizations, /api/GetDocumentList (02/14/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#20]
Severity: Medium

In the request to /api/GetDocumentList it is possible to specify caseid of the support case created in another organization. As a result, it is possible to access attachments of this support ticket

**Comment by shaileshtayde** [comment]
@prashantjadhav92 As mentioned in issue #6 
The case record can't be accessed by user until it is shared with resp. user OR it falls in case permission extension (or isPartnerAdmin) where if user has ability to view all case records of his current organization.

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked the above mentioned security issue it is possible for a user ("ishant.kshirsagar@revclerx.com") to get the document list of a case created by another user ("anuj.niet2010+01@gmail.com"). Both users are in different organizations and are not able to see the cases created by each of them. Both user are normal users.

**Comment by HareshKedar** [comment]
@PuneetRevclerx Kindly verify this on acronis2.sb.amp.vg

**Comment by PuneetRevclerx** [comment]
@HareshKedar sir, @sunrao sir, I have checked the above security issue and basic functionality on acronis2.sb.amp.vg and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 Sir, I have verified the above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
Confirmed by client.
