### ISSUE TITLE
#1474889 IDOR allows to delete export status, /api/DeleteContactExportEntries (02/14/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#21]
Severity: Low

It is possible to specify id of Export Entry from another organization and delete it

**Comment by shaileshtayde** [comment]
@Mahimapatil Please have resp. permission added.
1. Only current (creator) user can delete its resp. accessible record, hence the fileid.

**Comment by Mahimapatil** [comment]
@shaileshtayde PR https://github.com/MindMatrix/AMP/pull/48417

**Comment by shaileshtayde** [comment]
@prashantjadhav92 This is fixed and scheduled to release on 7th and for Acronis on 11th

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have Verifed above Security Issue on Production and Its Working fine as expected.

**Comment by prashantjadhav92** [comment]
I have asked the client to confirm the same.

**Comment by prashantjadhav92** [comment]
Confirmed by the client.
