### ISSUE TITLE
#1476281 Stored XSS in filters on images, documents, videos pages (02/14/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#22]
Severity: Medium

Make request to /api/SetFilters ( {"ids":[item_id],"filters":["filter"onclick=\"alert(1337)\""]}) and specify ID of any image,  and in filter add the following: onclick=\"alert(1337)\". After that open /#gallery/banner/images and find just created filter. Click on it and see JS executed

**Comment by PuneetRevclerx** [comment]
@shaileshtayde Sir, I have checked the above issue with normal user and JS is not getting executed by following above mentioned  steps.

User: puneet security
Company: Automation Tester

![image](https://user-images.githubusercontent.com/102346181/176364609-91d90d9c-a2b4-4ec9-93e6-6761ba9dc576.png)

**Comment by shivmishra** [comment]
https://github.com/MindMatrix/AMP/pull/51707
check here

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, @sunrao sir, I have checked the above security issue and basic functionality on the given branch (https://pr-51707.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify the same.
