### ISSUE TITLE
#1476378, #1476372, #1477734 XSS on company profile page in city, url,  linkedin, facebook and twitter fields (02/14/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#23]
Severity: Low

Make request to /api/SaveOrganization and specify the following in city, url, linkedin, facebook and twitter: https://google.com\"onmouseover=\"alert('XSS'). Go to company profile page and hover over the corresponding fields (city, url,  linkedin, facebook and twitter). See JS executed

**Comment by shaileshtayde** [comment]
@NagmaKadiri as mentioned in issue #15, this needs to be addressed.

**Comment by NagmaKadiri** [comment]
@shaileshtayde PR - #48700 created for testing.

**Comment by IshantRevclerx** [comment]
As per discussion with @shaileshtayde Sir, assigning it to @Mahimapatil.

Url : https://partners.acronis.com
User : lovish.bhatti@mm4.mindmatrix.net
XSS Used : "onmouseover=alert(1)//

**Comment by Mahimapatil** [comment]
@IshantRevclerx Fix has been merged on sandbox. It has been attached for build.

**Comment by IshantRevclerx** [comment]
@Mahimapatil mam, @sunrao Sir, I have checked above security issue on acronis sb ( https://acronis2.sb.amp.vg/ ) and It's working as expected now.

**Comment by Mahimapatil** [comment]
@PuneetRevclerx PR for this. https://github.com/MindMatrix/AMP/pull/52525

**Comment by prashantjadhav92** [comment]
I have asked the client to verify the fix.

**Comment by prashantjadhav92** [comment]
The fix has been verified.
