### ISSUE TITLE
#1476406 IDOR allows to read comments of documents from other organizations, /api/GetFeedbackCommentForItem (02/14/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#24]
Severity: Medium

In the request to /api/GetFeedbackCommentForItem it is possible to change itemid to the ID of the document located in another organizations and access the comments related to this document

**Comment by shaileshtayde** [comment]
@shivmishra Please add resp. permission for template/file so resp. user can only access and make comment on the same.

**Comment by shivmishra** [comment]
@sunrao @shaileshtayde  this is fixed here ask someone to test 
https://github.com/MindMatrix/AMP/pull/48276

**Comment by sunrao** [comment]
@shivmishra Mention the pages to be tested

**Comment by shivmishra** [comment]
its a feedback and rating graph display in many grids

**Comment by sunrao** [comment]
@YogeshRevclerx Pl. test this

**Comment by YogeshRevclerx** [comment]
@shivmishra I have tested this and this is working as expected.

![Untitled 1](https://user-images.githubusercontent.com/92095999/161310135-c7f2c93e-f9b2-4690-985f-6fbdb1d05375.png)
