### ISSUE TITLE
#1476406 IDOR allows to access files from other organizations, /feedback/<file_id>/2/comment (02/14/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#25]
Severity: Medium

It is possible to get direct links to files located in other organizations by specifying <file_id> in request /feedback/<file_id>/2/comment. “Asset name” is a direct link to a file

**Comment by shaileshtayde** [comment]
@shivmishra As mentioned in issue #14 
we'd need to implement permission check in GetFeedbackCommentForItem API + commenthistory.aspx.cs for resp. file/template id.
Also, please confirm if comment can be done to any logged-in user for any item or only accessible one?

**Comment by shivmishra** [comment]
@sunrao @shaileshtayde  this is fixed here ask someone to test 
https://github.com/MindMatrix/AMP/pull/48276

**Comment by sunrao** [comment]
@shivmishra Mention the pages to be tested

**Comment by shivmishra** [comment]
its a feedback and rating history page opening from templates/ files

**Comment by sunrao** [comment]
@YogeshRevclerx Pl. test this

**Comment by YogeshRevclerx** [comment]
@shivmishra I have tested this and the link containing other organization's document id is not accessible as it is showing the following error

![image](https://user-images.githubusercontent.com/92095999/161545645-552a7faa-62e2-41ec-8f9d-9a78cecae257.png)

**Comment by shivmishra** [comment]
ok, means that is fixed

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client to confirm.

**Comment by prashantjadhav92** [comment]
Confirmed by the client.
