### ISSUE TITLE
#1476120 IDOR allows to add comments to documents located in other organizations, /api/UpdateComments (02/14/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#26]
Severity: Low 

In the request to /api/UpdateComments ({"itemid":[item_id],"comment":"[your_comment]","type":2}}}) it is possible to specify file ID in itemid and any comment in the corresponding field to add comment to a document from another organizations. Is it supposed behavior?

**Comment by shaileshtayde** [comment]
@shivmishra related to issue #25. Please confirm.

**Comment by shivmishra** [comment]
@sunrao @shaileshtayde  this is fixed here ask someone to test 
https://github.com/MindMatrix/AMP/pull/48276

**Comment by sunrao** [comment]
@shivmishra Mention the pages to be tested

**Comment by shivmishra** [comment]
its a common api calling from every grid to add comments

**Comment by sunrao** [comment]
@YogeshRevclerx Pl. test this

**Comment by YogeshRevclerx** [comment]
@shivmishra I have tested it on the branch and it has been fixed. User cannot update the comments of other organization's documents and templates.

![API 1](https://user-images.githubusercontent.com/92095999/161087134-76036e7f-4ae1-4cf6-8ef0-84b24807abf0.png)

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 Sir, I have checked the above mentioned security issue and its resolved now.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx I have asked the client to confirm.

**Comment by prashantjadhav92** [comment]
Confirmed by client.
