### ISSUE TITLE
#1478438 IDOR on /connections/list/<LIST_ID>/info allows access to lists from other organizations (02/14/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#27]
Severity: Medium

It is possible to specify any <LIST_ID> and access corresponding list, even if it was created in another organization

**Comment by shaileshtayde** [comment]
@shivmishra As of now, use can access the contact list even if the list created in the same company.
![image](https://user-images.githubusercontent.com/6465652/159144428-60e0fcbf-e3b2-4e53-8090-a49ba7360ce0.png)

@shivmishra @prashantjadhav92 @sunrao Please confirm if this should have the same check?
@cphillips83 fyi

**Comment by shivmishra** [comment]
@sunrao @shaileshtayde this is fixed here ask someone to test
https://github.com/MindMatrix/AMP/pull/48276

**Comment by sunrao** [comment]
@shivmishra Mention the pages to be tested

**Comment by shivmishra** [comment]
its a list info page but permission is common so check diffrent types of lists info to open info page

**Comment by sunrao** [comment]
@Apeksha1 Give a run

**Comment by Apeksha1** [comment]
@shivmishra : Working as expected.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked the above mentioned security issue and its working as expected now.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx I have asked the client to confirm this point.
