### ISSUE TITLE
#1478438 IDOR on /api/SaveListInfo allows to change to list located in another organizations

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#28]
Severity: Medium

It is possible to specify any “listid” and corresponding “distributionid” (which might be found on /connections/list/<LIST_ID>/info) and change the list, even if it is located in another organization

**Comment by shivmishra** [comment]
@sunrao @shaileshtayde this is fixed here ask someone to test
https://github.com/MindMatrix/AMP/pull/48276

**Comment by sunrao** [comment]
@shivmishra Mention the pages to be tested

**Comment by shivmishra** [comment]
its saving of list info page

**Comment by sunrao** [comment]
@Apeksha1 Pl. test this

**Comment by Apeksha1** [comment]
@shivmishra : Working as expected. Closing this issue.
#NOTE: Tested using POSTMAN
