### ISSUE TITLE
8x8 Security issue - IDOR allows to delete customer social media post/drip.

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#30]
Steps To Reproduce

1. Login.
2. Visit these vulnerable pages
https://refer.8x8.com/#communicate/social
https://refer.8x8.com/#manage/campaigns/socialdrip.
3. Intercept the request before deleting the social media post/drip.
4. Change the media ID to any media of another account.
[VULN-1006.pdf](https://github.com/MindMatrix/SecurityTracker/files/8225717/VULN-1006.pdf)

**Comment by prashantjadhav92** [comment]
@shaileshtayde @tajindersharma @cphillips83 this is a critical issue marked by client and has been pending for update since past few weeks. Can we please have this one looked into on priority?

**Comment by shaileshtayde** [comment]
@tajindersharma Please confirm. 
If you need to make any business decision, please have this discussed with  @sunrao about roles/permissions

**Comment by tajindersharma** [comment]
@shaileshtayde I have fixed this in https://dvl-security-issue-30.amp.vg/
Can you please get this tested once?

**Comment by shaileshtayde** [comment]
@sunrao Please do the needful

**Comment by sunrao** [comment]
@Rohitharidas Pl. test this on the branch

**Comment by Rohitharidas** [comment]
@tajindersharma Please send PR for release

**Comment by prashantjadhav92** [comment]
@tajindersharma when can we expect this to be released?

**Comment by tajindersharma** [comment]
@prashantjadhav92  This will be done in this week's release

**Comment by prashantjadhav92** [comment]
@tajindersharma @shaileshtayde is this released on 8x8 prod?

**Comment by tajindersharma** [comment]
Yes, it should be on 8x8 prod

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir,Verified above issue and its Resolved now.
