### ISSUE TITLE
#1424730 XSS via company name

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#36]
1. It is possible to set company name on /api/SaveOrganization, in field “name”, e.g. using the following payload:
test\" onload=\"alert('xss via company name')\"
2. When company name is changed, 
go to /#user/profile/ -> Company and set Company logo
3. Save profile
4. Open any video preview and see XSS executed

**Comment by shaileshtayde** [comment]
@shivmishra we've fixed this one already but have this confirmed again.

**Comment by prashantjadhav92** [comment]
@shivmishra I will ask the client to confirm this.
