### ISSUE TITLE
#1444021 Missing session invalidation on password change

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#38]
There is no session invalidation on password change. Steps to reproduce:
- Login to your account in browser1
- In browser2 change the password for this account
- Go to browser1 and see that session is still active

**Comment by PuneetRevclerx** [comment]
@shaileshtayde Sir, I have checked the issue by following above mentioned steps and there is no session invalidation on password change.

**Comment by shaileshtayde** [comment]
@sunrao @PuneetRevclerx @IshantRevclerx This is addressed in main branch, please have this tested.

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have tested it on main and still after changing the password on 1 browser the session stays active in the second browser.

**Comment by shaileshtayde** [comment]
@PuneetRevclerx Did you build the main branch? If not, please do so. I've rebuild again

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, The above issue is fixed for reset password functionality. Kindly check the video for reference. 
Kindly confirm if the same changes need to be done on the change password functionality as well?


https://user-images.githubusercontent.com/92088937/195130825-e294632f-5c7a-4815-9c8b-4247a1faffbf.mp4

**Comment by IshantRevclerx** [comment]
@shaileshtayde sir, as mentioned by prashant sir kindly make the changes in change password functinality as well.

**Comment by shaileshtayde** [comment]
@prashantjadhav92 When you ask for this functionality, what do you mean?
1. Do you mean to terminate all  the active sessions including current one?
2. Or keep the active one and terminate rest of the sessions?

This needs to be confirmed @cphillips83 @sunrao what is your point of view on this one?

**Comment by sunrao** [comment]
This was done earlier wherein it used to terminate all existing sessions, can we make this configurable?

**Comment by shaileshtayde** [comment]
@cphillips83 please comment

**Comment by sunrao** [comment]
@PuneetRevclerx Pl. test this

**Comment by PuneetRevclerx** [comment]
@tajindersharma sir, @sunrao sir, I have checked above security issue on the given branch (http://pr-53532.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@vickypoonia, As discussed with @shaileshtayde sir, if user changes his password with checkbox checked then he should get redirected to the login page in his current session.

**Comment by PuneetRevclerx** [comment]
@vickypoonia, @sunrao sir, I have checked above security issue on the given branch (https://pr-53377.dvl.amp.vg) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx I have asked the client to confirm the fix.

**Comment by prashantjadhav92** [comment]
Verified by the client.
