### ISSUE TITLE
#1430212 Stored XSS via case name at partners.acronis.coms (01/11/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#4]
**Severity: Medium**

The case name is vulnerable to XSS (https://partners.acronis.com/#manage/support)

**Comment by shaileshtayde** [comment]
@prashantjadhav92 This is verified and no longer an issue.

**Comment by prashantjadhav92** [comment]
@shaileshtayde Acronis has claimed this to be reproducible. Please confirm again.

**Comment by PuneetRevclerx** [comment]
@shaileshtayde Sir, I have checked the above mentioned issue and JS is getting executed by following the below mentioned steps:

1. On https://acronis2.sb.amp.vg/#manage/support, click on "Submit a Case" and add ["onmouseover=alert(1)//] in the case summery field.
2. Fill the required fields and save the case.
3. Hover the mouse on newly created case subject in the grid.
4. JS will execute.

User email: ishant.kshirsagar@revclerx.com

![image](https://user-images.githubusercontent.com/102346181/176890349-2b1815a9-03e9-47bb-84f8-93bbae7825d9.png)

**Comment by HareshKedar** [comment]
@PuneetRevclerx Kindly verify on acronis2.sb.amp.vg

**Comment by PuneetRevclerx** [comment]
@HareshKedar sir, @sunrao sir, I have checked the above security issue and basic functionality on the acronis2.sb.amp.vg and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify this.

**Comment by prashantjadhav92** [comment]
Verified by the client.
