### ISSUE TITLE
8x8 Security issue - Alert message is apearing again in the media part of Email.

### ISSUE THREAD

**Issue by YogeshRevclerx** [MindMatrix/SecurityTracker#41]
URL:- https://mm.amp.vg/#communicate/email
User:- Yogesh

STR

Communicate>> Email>> Go with blank template>> On editor, Add text object>> Add alert message on SVG into it.>> Save it and click on Preview.
![image](https://user-images.githubusercontent.com/92095999/163329333-35155aa5-8c6d-4d8d-8282-b9d874ed9e4c.png)

**Actual Result:-** The alert message will appear after clicking on the preview.

![image](https://user-images.githubusercontent.com/92095999/163329161-9f00f0f6-abcf-42d7-abe8-09923d05de35.png)

**Note:-** This is working fine on the Main (dvl-main.amp.vg) and template side of the Live (mm.amp.vg).

**Comment by sunrao** [comment]
@YogeshRevclerx Once clear all cache and cookies and check on LIVE, if it is working on Main and if still, the issue exists then ask @Vish-Patil to look into it

**Comment by sunrao** [comment]
@Vish-Patil Can you pl check this?

**Comment by YogeshRevclerx** [comment]
@sunrao sir, I have checked it after clearing the cache and cookies, still showing the same.

**Comment by Vish-Patil** [comment]
main has strictxmlsanitization set as true, so issue will not come in main. 
please check in any other branch
Issue is resolved in this branch dvl-security-41.amp.vg, please get it tested once its build successfully.

**Comment by YogeshRevclerx** [comment]
@Vish-Patil Sir, This message is appearing on Send email page. but in the editor and its preview, it is working fine.

![image](https://user-images.githubusercontent.com/92095999/163755212-d9f36b8d-028d-422d-9dbf-60b52dcb659e.png)

**Comment by YogeshRevclerx** [comment]
@Vish-Patil after commit, I have checked this on the branch. and it is working as expected. Please send this PR for release.

![image](https://user-images.githubusercontent.com/92095999/164062818-0d88c57e-7f8f-4639-9686-c46bcc92f304.png)
