### ISSUE TITLE
[VULN-1099] SSRF lead to LFI on refer.8x8.com SEC-4603

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#42]
Local files on the Windows machines can be accessed via an LFI.
Details as attached.
[[#VULN-1099] [H1] SSRF lead to LFI on refer.8x8.com (Mind Matrix).pdf](https://github.com/MindMatrix/SecurityTracker/files/8709732/VULN-1099.H1.SSRF.lead.to.LFI.on.refer.8x8.com.Mind.Matrix.pdf)

**Comment by prashantjadhav92** [comment]
@shaileshtayde 8x8 is asking for an update on this point. Can you please get this checked on priority?

**Comment by prashantjadhav92** [comment]
@shaileshtayde This has now been reported by Acronis too. Can we get an update on this?

**Comment by prashantjadhav92** [comment]
@cphillips83 @shaileshtayde can this be checked on priority as this issue has been reported by both Acronis and 8x8. The 8x8 client has asked for an update multiple times on this.
If we can atleast get an ETA that would be helpful.

**Comment by shaileshtayde** [comment]
I'll review this today on priority. I was busy with tickets + Lenovo, hence
didn't get a chance to look into this.

Shailesh

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir I have Checked above issue and by following the mention steps user can access files on local machine via LFI.

![8X8 ScreenShoot](https://user-images.githubusercontent.com/92088937/173005047-a1c5b5e1-fa82-4b85-b1c5-2f759da32e68.png)

**Comment by prashantjadhav92** [comment]
@shaileshtayde can we please get this one resolved. 8x8 team has marked this as critical and needs the issue to be fixed as soon as possible. They have been following up with us multiple times but I don't have proper updates to share with them.

**Comment by cphillips83** [comment]
@prashantjadhav92 I had to send an email to ABCPDF for more information since we use their libraries to generate these PDFs.

**Comment by prashantjadhav92** [comment]
Thank you @cphillips83

**Comment by prashantjadhav92** [comment]
@cphillips83 do we have any update on this point?

**Comment by cphillips83** [comment]
@prashantjadhav92 https://github.com/MindMatrix/AMP/pull/53000 fixes this issue

**Comment by prashantjadhav92** [comment]
@sunrao you have closed this issue. Can you please let me know if this is fixed?

**Comment by prashantjadhav92** [comment]
@cphillips83, can you please let me know if this point was fixed?

**Comment by sunrao** [comment]
@IshantRevclerx Pl. test this on the LIVE

**Comment by IshantRevclerx** [comment]
@sunrao sir,  I have checked on Print template and eBook , Its working as expected

**Comment by prashantjadhav92** [comment]
@IshantRevclerx was this tested on Acronis production?

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, this issue was reported by 8X8 but we verified on Acronis production and its working as expected now.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client to confirm.
