### ISSUE TITLE
#1451564 IDOR allows to copy other organizations’ social media post/drip, /api/CopyPublishing

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#45]
In the request to /api/CopyPublishing (sent by user from <organization1>)  it is possible to specify media ID of media from any other organization. It will be copied to <organization1> and its content will be accessible

**Comment by PuneetRevclerx** [comment]
@shaileshtayde Sir, I have checked the above mentioned issue and only a super admin user can copy the social drip of any user from other organization and not the normal user. There is no option available for the super admin user to copy social drip of a user from other organization on the UI but he can do so by following above mentioned steps.
User: puneet security
Company- Automation Tester

In the screenshot, only the media side of the drip is shown which is copied from a user of other organization and not the template for the same drip.
![Social Drip copy](https://user-images.githubusercontent.com/102346181/173755934-24797de9-bf62-437e-992d-a43a5b6c659a.png)

**Comment by PuneetRevclerx** [comment]
@shaileshtayde Sir, as mentioned above, the above issue is not for normal user.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked the above mentioned security issue and it's resolved now.

**Comment by prashantjadhav92** [comment]
Verified by the client.
