### ISSUE TITLE
#1451676 IDOR allows to copy other organizations’ drip campaign, /api/deletedrip

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#47]
In the request to /api/deletedrip it is possible to specify drip ID of drip campaign from any other organization. This drip campaign will be deleted as a result

**Comment by PuneetRevclerx** [comment]
@shaileshtayde Sir, I have checked the above issue and it is possible for a user to delete a drip of any user from other organization by only changing the drip id in the payload of "/api/deletedrip".

![Drip available](https://user-images.githubusercontent.com/102346181/173495490-ee8ec9b4-b2d2-4259-9c4c-271866914f1f.png)

Test template drip was deleted using drip id by other user.
![Drip deleted](https://user-images.githubusercontent.com/102346181/173495510-2f765082-0a00-49c4-b577-f62f1c9e58d8.png)

**Comment by PuneetRevclerx** [comment]
Users: puneet security and security ishant (Both normal users)
Company- Automation Testers

**Comment by Mahimapatil** [comment]
@PuneetRevclerx It is duplicate issue of https://github.com/MindMatrix/SecurityTracker/issues/47. Please delete one of them.

**Comment by sdokhale0902** [comment]
@prashantjadhav92 . Please Check now. Branch-url : https://dvl-pr-50131.amp.vg/

**Comment by sunrao** [comment]
@PuneetRevclerx Pl. test this

**Comment by Mahimapatil** [comment]
@sdokhale0902 You didnt create PR of this?

**Comment by PuneetRevclerx** [comment]
@Mahimapatil mam, I have checked the above issue on https://pr-50131.dvl.amp.vg/ and the user is still able to delete drip created by the user in different organization.

**Comment by sdokhale0902** [comment]
@PuneetRevclerx. Please Check on these branch url:  https://pr-51031.dvl.amp.vg/

**Comment by PuneetRevclerx** [comment]
@Mahimapatil mam, @sunrao sir, I have tested above mentioned above mentioned security issue and it's working as expected. 

@sunrao sir, kindly assign it to respective tester for functionality testing.

**Comment by sunrao** [comment]
@PuneetRevclerx You can do the functionality test and the Tester will do it during the Main run

**Comment by PuneetRevclerx** [comment]
@sunrao sir, I have tested the functionality of above mentioned issue and it's working as expected.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, above security issue has been resolved and I have verified it on production.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx I have asked the client to confirm.

**Comment by prashantjadhav92** [comment]
Verified by the client.
