### ISSUE TITLE
#1452207 (1) IDOR allows to add messages to other organizations’ drip, /api/SavePublishingMessage

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#48]
In the request to /api/SavePublishingMessage it is possible to specify publishingid to drip ID from any other organization. As a result, it is possible to add publishing messages to drip in other organizations.

**Comment by IshantRevclerx** [comment]
@shaileshtayde sir I have Checked above issue and user can add any publishing Massage to drip in other organization.

![API Test05](https://user-images.githubusercontent.com/92088937/173064436-62251158-c7e2-4b63-a624-4b30af633394.png)

**Comment by IshantRevclerx** [comment]
@shaileshtayde  Sir, The above issue is not for the Normal user.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have Checked above mentioned Security Issue and Its Resolved Now.

**Comment by prashantjadhav92** [comment]
Asked the client to confirm.

**Comment by prashantjadhav92** [comment]
Verified by the client.
