### ISSUE TITLE
#1452207 (2) IDOR allows to publish other organizations’ drip campaign, /api/RestartPublishing

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#49]
In the request to /api/RestartPublishing it is possible to specify publishingid to drip ID from any other organization. As a result, it is possible to publish drip from other organizations. Together with #1452207 
(1) it might be possible to publish messages on behalf of other organizations in their social media (assuming social media was configured in drip)

**Comment by IshantRevclerx** [comment]
@shaileshtayde I have Checked above issue, this issue exist. 
It is possible to publish drip from other organizations.
![Drip Status](https://user-images.githubusercontent.com/92088937/173358898-08f01779-57b3-436c-b45a-5619042d1a94.png)
After Changing the Status via API.
![Drip Status-2](https://user-images.githubusercontent.com/92088937/173358957-a53fd855-f856-4499-80c4-193c9d8b064e.png)

**Comment by IshantRevclerx** [comment]
@Shailesh Sir, The above Issue is not for the Normal user.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have checked above mentioned Security Issue and its Resolved Now.

**Comment by prashantjadhav92** [comment]
I have asked the client to test it.

**Comment by prashantjadhav92** [comment]
Verified the fix.
