### ISSUE TITLE
#1436013 Stored XSS via activity name on MDF page (01/11/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#5]
**Severity: Medium**

XSS when you view project -> activity name

**Comment by shaileshtayde** [comment]
@prashantjadhav92 This has been verified and is not reproduceable anymore.

**Comment by prashantjadhav92** [comment]
@shaileshtayde Acronis has claimed this to be reproducible. Please confirm again.

**Comment by shaileshtayde** [comment]
@Vish-Patil Please look into this.

**Comment by Vish-Patil** [comment]
@sunrao please get this tested in following PR
https://github.com/MindMatrix/AMP/pull/52996

**Comment by PuneetRevclerx** [comment]
@Vish-Patil sir, @sunrao sir, I have checked above security issue on Acronis Sandbox and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx I have asked the client to confirm.
