### ISSUE TITLE
#1476406 IDOR allows to read comments of documents from other organizations, /api/GetFeedbackCommentForItem

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#50]
In the request to /api/GetFeedbackCommentForItem it is possible to change itemid to the ID of the document located in another organizations and access the comments related to this document

**Comment by PuneetRevclerx** [comment]
@shaileshtayde Sir, I have checked the above mentioned issue and it is possible for a user to access the comments related to a document of a user in other organization by changing the item ID of the document in "/api/GetFeedbackCommentForItem".

Users: puneet and roger
Company: mindmatrix

**Comment by shivmishra** [comment]
@PuneetRevclerx I cannot explain you, are these both users are Superadmin. do you know the accessibility level of Superadmin.
if you will check with these users you will get issue everywhere.
@shaileshtayde fyi both are superadmin users

**Comment by PuneetRevclerx** [comment]
@shaileshtayde Ok sir

**Comment by IshantRevclerx** [comment]
@shaileshtayde Ok sir will takecare of next time.

**Comment by shivmishra** [comment]
also don't check with users who have (user-> create & organization -> create) both. They are treated as Superadmin to get access data of company users.

**Comment by PuneetRevclerx** [comment]
@shivmishra ok sir, now we are checking with a user who has user permission = delete and organizations_users & organization_profile both = view permission.

**Comment by PuneetRevclerx** [comment]
@shaileshtayde Sir, the above issue not for the normal user.

**Comment by shaileshtayde** [comment]
@prashantjadhav92 as @shivmishra & @PuneetRevclerx confirmed, these issues are not reproduceable for users having proper permissions.
@prashantjadhav92 Please confirm what users they are trying with? if it is _SuperAdmin_, the it will work.
