### ISSUE TITLE
#1449932 Stored XSS using file renamin

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#52]
It is possible to change uploaded file extension to .svg, which leads to Cross-Site Scripting attack possibility. For example, the following file was uploaded: https://partners.acronis.com/file/ccweldtavhlnc/svg.txt, if extension is changed to .svg, XSS payload will be executed: https://partners.acronis.com/file/ccweldtavhlnc/svg.svg

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, It's a duplicate issue of #141
