### ISSUE TITLE
SEC-4427 Account takeover via IDOR using API endpoint /api/SendTemporaryPassword

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#54]
Account takeover via IDOR using API endpoint /api/SendTemporaryPassword, since this endpoint allows to send password reset link for existing users in the same organization. Additionally, this is not possible in UI

Steps to Reproduce:

Send POST request to /api/SendTemporaryPassword with the following body

{"userid":<USER_ID>,"sendemailto":1,"recipient":"","linkid":0,"linktype":2,"ismultiplecontactconversion":false}

FIx: for existing users it should only be possible to send password reset link to their email address

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have Checked above mentioned issue and user can takeover any other user account in his organization as well as in any other  organization.
UserName : Security Ishant / Puneet Security
Temporary email sent  on 16-6-2022 to ishant.kshirsagar@revclerx.com
![Temprory Mail-1](https://user-images.githubusercontent.com/92088937/174014249-114aefb3-cd8a-4238-bbef-a2d31007e9ba.png)

And user was created on 10-6-2022 has already accepted TOS
![Temprory Mail-2](https://user-images.githubusercontent.com/92088937/174014340-f1039e5a-2326-4780-b4d2-6c47c0c2e2a8.png)

**Comment by shivmishra** [comment]
@prashantjadhav92 @shaileshtayde @IshantRevclerx yes thats the feature and its can be done only user who have user create role

**Comment by shivmishra** [comment]
also added one extra check to prevent the api, only on user creation temporary pasword can be send after login the user no temporary password can be send. so please check accordingly.

fixed here https://github.com/MindMatrix/AMP/pull/51106

@sunrao fyi.

**Comment by IshantRevclerx** [comment]
@sunrao Sir and @shivmishra Sir, I have checked above mentioned security Issue and its working as expected.
@sunrao sir please assign to respective tester to test functionality.

**Comment by IshantRevclerx** [comment]
@sunrao Sir, I have checked the functionality as it was similar to the other ticket in the PR and its working as expected

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have cheked above mention security issue on production and its working fine as expected now.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client to confirm the same.

**Comment by prashantjadhav92** [comment]
Client confirmed this to be fixed.
