### ISSUE TITLE
SEC-4357 Email change without password confirmation

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#55]
It is possible to change email without password confirmation. As a result, such issues as XSS can lead to account takeover

Steps to Reproduce:
* Send POST request to /api/SetProfileData with the following body
{"json":{"email":"<NEW_EMAIL_ADDRESS>"},"notifymebyemail":false,"language":8}

Fix: require password confirmation for email change

**Comment by PuneetRevclerx** [comment]
@shaileshtayde A normal user does not have any option available on UI to change his Email id in View Profile. But user can change his email id by following the above mentioned steps.

Originally user's email id was "ishantrevclerx@mailinator.com"
![Normal User email](https://user-images.githubusercontent.com/102346181/172995673-0c7c1892-5bbd-448d-ba17-faea1982e39d.png)

After following the above mentioned steps, user's email id changed to "ishantrevclerx@gmail.com"
![Normal User changed email](https://user-images.githubusercontent.com/102346181/172995848-2b7db61d-2cb6-4725-8b20-5747223f4077.png)

**Comment by shaileshtayde** [comment]
@shivmishra I believe, only SA user has privilege to change the email id of his company user. So, when email address is changed, we'd need to either check for SA when email is changed or remove the email address from this API, if we'd need to

**Comment by PuneetRevclerx** [comment]
@shaileshtayde @shivmishra Sir, I have checked above issue on given branch "https://dvl-pr-50389.amp.vg/" and it's working as expected now.

@sunrao Sir, I have tested the security part, kindly have the functionality tested.

**Comment by shaileshtayde** [comment]
In order to have this functionality tested, this can be tested using Super/Site Admin user from UI under setup. 
@PuneetRevclerx give a single run from your end and then assign it back to @sunrao for the feature testing.

**Comment by sunrao** [comment]
@PuneetRevclerx You can give the functionality run and if needed take help from Parveen

**Comment by shivmishra** [comment]
team, except sitesuperadmin and self user can change email/username nothing got changed in the code

**Comment by shaileshtayde** [comment]
@sunrao please have resp tester give a run on reps functionality as well. We need to make sure that module owner must sign off as well.

**Comment by PuneetRevclerx** [comment]
@sunrao sir, I have checked the functionality and it's working fine.

**Comment by prashantjadhav92** [comment]
I have asked the Acronis team to check and confirm this. Once it is confirmed to be working fine, I will close this case.

**Comment by prashantjadhav92** [comment]
@sunrao @PuneetRevclerx @shaileshtayde the client has shared this video. It is still possible to change the email address without password confirmation on /api/SetProfileData.

https://user-images.githubusercontent.com/31324885/177586131-ea5821f2-2b57-4379-8acf-80e3fd3da4bd.mp4

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 Sir, above mentioned issue along with #53 , #51 and #61 are still needs to be pushed on production. The PR has been merged to the "dvl-main" and will be pushed on production today. That's why client is still able to reproduce the issue on production.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx thank you for confirming. Please assign the case to me only when it is released on production.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 Sir, I have checked the above security issue on production and its working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to confirm the same.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx client has mentioned this is still reproducible. Please check and confirm again.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 Sir, I have tested it again at my end and it's working fine for me. Kindly provide the users and scenarios so that I can verity it.

**Comment by prashantjadhav92** [comment]
Confirmed this to be fixed.
