### ISSUE TITLE
SEC-4426 Same organization account takover via IDOR vulnerability (/api/ConvertPartnerToUser)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#56]
It is possible to takeover accounts in the same organization due to IDOR vulnerability in /api/ConvertPartnerToUser

Steps to Reproduce:
In POST request to API endpoint /api/ConvertPartnerToUser it is possible to specify userid of any user in the same organization and change email address to your own.

{"userid":<VICTIM_USER_ID>,"syncusername":null,"groups":[],"json":{"email":"<ATTACKER_CONTROLLED_EMAIL>"},"contactid":<ANY_CONTACT_ID>,"cfjson":{}}

Fix: It should not be possible to change email address of other users, even in the same organization (from what we can see, UI already does not allow this)

**Comment by PuneetRevclerx** [comment]
@shaileshtayde Sir, I have check the above mentioned issue. By using "/api/ConvertPartnerToUser" API, user can change the email address of **any user in the same organization as well as in any other organization**. Along with email id, user can also change username, first name, last name etc. as well.

![Old user data](https://user-images.githubusercontent.com/102346181/173501490-07a876e2-4ef7-4f48-9259-b988df3e9006.png)

Username, Email, First Name and Last name of the same user is changed using the above mentioned steps.
![new user data](https://user-images.githubusercontent.com/102346181/173501510-5568d3e3-76db-4792-bb06-16907086d299.png)

**Comment by PuneetRevclerx** [comment]
User: puneet security
Company: Automation Tester

**Comment by MeghanaThakekar** [comment]
@shaileshtayde @PuneetRevclerx - fixed
branch : "https://dvl-securityissue-56.amp.vg/"
@sunrao - test user creation and convert contact to user feature

**Comment by PuneetRevclerx** [comment]
@MeghanaThakekar given branch is not working

![image](https://user-images.githubusercontent.com/102346181/175209309-a6395268-8464-4c62-94d0-837fab79441c.png)

**Comment by shaileshtayde** [comment]
@***@***.*** ***@***.***> This is due to a
build server issue. This should be good to go once @Chris Phillips
***@***.***> fix it up.

Shailesh

**Comment by MeghanaThakekar** [comment]
@PuneetRevclerx - new url:  https://dvl-pr-50282.amp.vg/login

**Comment by PuneetRevclerx** [comment]
@MeghanaThakekar given branch is not working: 
![image](https://user-images.githubusercontent.com/102346181/175858579-3d8de5bf-7759-469f-9bb4-4732ea06c9dd.png)

**Comment by PuneetRevclerx** [comment]
@MeghanaThakekar branch is working now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, the above security issue has been resolved. I have checked it on production and it's working as expected.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx I have asked the client to confirm.

**Comment by prashantjadhav92** [comment]
Verified by the client.
