### ISSUE TITLE
SEC-3777 Stored XSS in web banners customization, via "Google script" field

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#57]
Stored XSS via HTML page creation. This issue was already reported in support ticket 74939 (#1406096), but was not fully fixed, since vulnerable field was just hidden on frontent.

Steps to reproduce:
    a. Open customization for any web banner and go to Web Banner Editor -> Settings -> Meta Information
    b. Open browser Developer Tools -> Inspector. In Inspector search for "Scripts and Styling". In enclosing div element remove style="display: none;"
    b. Insert any script in "Scripts and Styling" field which should now be visible, e.g. <script>alert(1)</script>
    c. Finish web banner customization and get the link
    d. Open the link and see JavaScript payload executed

Fix: It is not enough to hide the field, it should be completely removed, in API as well

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir Same tickets is alredy created under - #59 

We have alredy verified #59.

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir and @prashantjadhav92 Sir, Its Duplicate ticket of #59, hence closing this ticket.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx @shaileshtayde Acronis has mentioned that they are now able to reproduce this issue using the below steps:

It was not possible through UI, however they were able to send the request with the following body to API directly (POST /api/SavePage) and add XSS payload.

You can check out https://partners.acronis.com/web/5kjudxww65f8, which they have updated today.

POST request body (you can see <script>alert(2)</script> payload in the request):
{"pageid":112943,"mobilepage":0,"externalTemplateXML":"<ExternalTemplates></ExternalTemplates>","pagexml":"<page padding=\"0\" bordercolor=\"#ffffff\" borderwidth=\"0px\" borderstyle=\"none\" totalwebnavigationtabs=\"0\" associatedto=\"0\" pageid=\"112943\" iswebnavinserted=\"0\" showinwebnav=\"false\" nextid=\"13\" objectmmid=\"0\" disconnected=\"False\" pagerotate=\"0\" backgroundimage=\"\" backgroundcolor=\"#FFFFFF\" pagetitle=\"Promotion Banner4\" printmargin=\"0\" height=\"90\" width=\"728\" ispageoverflow=\"false\" islock=\"false\" noofpages=\"0\" masterpageid=\"0\" ismasterpage=\"0\" ischanged=\"1\" fitbgimage=\"false\"  pageanimation=\"\" isgotowebinar=\"false\" isemailpage=\"false\" sourceid=\"0\" pageduration=\"undefined\" backgroundvideo=\"undefined\" bgvideostarttime=\"0\" bgvideoduration=\"0\" islocksection=\"false\" ismapscenetobgvideo=\"false\" companyorgcolor=\"undefined\"><image id='objectCustomProperties' objecttype='image' objectmmid='2' width='728px' height='90px' top='0px' left='0px' borderthickness='1px' bordercolor='' borderstyle='0' backgroundcolor='' layername='ImageObject Layer' lockforreference='0' islinked='0' zindex='102' visible='1' itemlinkid='0' itemlinkto='24' locksizeandposition='0' dbelementid='0' islocked='0' cssname='' objectflow='0' repeaterid='1' position='absolute' groupname='' behavior='' previewanimation='' duration='2s' delay='0s' objectorder='2' opacity='1' borderradius='0px' background='' companycolor='0' brcompanycolor='0' imagetype='1' imgtop='0' imgleft='0' imgheight='90px' imgwidth='728px' alignment='0' v-alignment='0' datafield='0' imgpropertysrc='' imageindex='0' imageid='0' imageurl='https://partners.acronis.com/oimg/zauqga7dgska/optimized-Promotion_Banner4.png' url='' imagetag='' rotvalue='0' imagestretchtype='0' croppedimage='0' croppedimagesrc='' lockcontent='0' lockstyle='0' transformmatrix='matrix(1,0,0,1,0,0)' animationrank='0' animationtype='none' animationdirection='' ishotspotimage='false' ><url><![CDATA[]]></url></image><image id='objectCustomProperties' objecttype='image' objectmmid='3' width='78px' height='27px' top='5px' left='260px' borderthickness='1px' bordercolor='' borderstyle='0' backgroundcolor='' layername='ImageObject Layer' lockforreference='0' islinked='0' zindex='103' visible='1' itemlinkid='0' itemlinkto='##organization.PhotoID##' locksizeandposition='0' dbelementid='0' islocked='0' cssname='' objectflow='0' repeaterid='1' position='absolute' groupname='' behavior='' previewanimation='' duration='2s' delay='0s' objectorder='3' opacity='1' borderradius='0px' background='' companycolor='0' brcompanycolor='0' imagetype='1' imgtop='0' imgleft='0' imgheight='27px' imgwidth='32.4px' alignment='2' v-alignment='0' datafield='0' imgpropertysrc='' imageindex='0' imageid='0' imageurl='https://partners.acronis.com/oimg/cihbxwu97oo3w/optimized-6.jpg' url='' imagetag='' rotvalue='0' imagestretchtype='0' croppedimage='0' croppedimagesrc='' lockcontent='0' lockstyle='0' transformmatrix='matrix(1,0,0,1,0,0)' animationrank='0' animationtype='none' animationdirection='' ishotspotimage='false' ><url><![CDATA[]]></url></image><placeholder id=\"objectCustomProperties\" objecttype=\"placeholder\" objectmmid=\"1\" width=\"1759px\" height=\"90px\" top=\"0px\" left=\"-528px\" borderthickness=\"1px\" bordercolor=\"\" borderstyle=\"0\" backgroundcolor=\"\" layername=\"Section Layer\" lockforreference=\"0\" islinked=\"0\" zindex=\"auto\" visible=\"1\" itemlinkid=\"0\" itemlinkto=\"0\" locksizeandposition=\"0\" dbelementid=\"0\" islocked=\"0\" cssname=\"\" objectflow=\"0\" repeaterid=\"0\" position=\"relative\" groupname=\"\" behavior=\"\" previewanimation=\"\" duration=\"2s\" delay=\"0s\" objectorder=\"1\" opacity=\"1\" borderradius=\"0px\" background=\"\" companycolor=\"0\" brcompanycolor=\"0\" backgroundimage=\"\" stretchtofull=\"1\" bgrepeat=\"0\" bgsize=\"0\" bgposition=\"0\" heightautoincreased=\"0\" ></placeholder><behaviors></behaviors><metadatainformation><pagetitle><![CDATA[Promotion Banner4]]></pagetitle><metadescription><![CDATA[test]]></metadescription><metakeywords><![CDATA[]]></metakeywords><metaimage><![CDATA[]]></metaimage><metakeywordsh1><![CDATA[]]></metakeywordsh1><metakeywordsh2><![CDATA[]]></metakeywordsh2><metakeywordsh3><![CDATA[]]></metakeywordsh3><googleanalytics><![CDATA[<script>alert(2)</script>]]></googleanalytics><pagescript><![CDATA[]]></pagescript><googletrackingcode><![CDATA[]]></googletrackingcode></metadatainformation><datasources objectmmid=\"10\"></datasources>projectXML<projectsources></projectsources></page>","theme":"","emailAlign":"0","pgmgmtxml":"<rules></rules>","btnXml":"","subject":"","makeemailreusable":false,"savepage":true, "reusablename":"","iswireframe":false,"islocksection":false,"shoinweb":false, "formidforpage":0,"emailid":0,"isforapproval":false,"deletedobjectids":"","webAlign":"1" ,"isEmailResponsive":false,"strplaceholderorder":"1,","previewText":"","isInteractiveBanner" :true,"uniquesign":0,"isGoToWebinar":false,"pauseAnimation":false,"templateid":123454}

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir and @shaileshtayde sir, I have checked above issue with the given payload but issue not getting reproduce at my end

**Comment by shaileshtayde** [comment]
Adding @Vish-Patil to provide his feedback on this one.

**Comment by prashantjadhav92** [comment]
@Vish-Patil can you please provide your feedback as soon as possible.

**Comment by Vish-Patil** [comment]
@shaileshtayde this has been done in https://github.com/MindMatrix/AMP/pull/53840

**Comment by PuneetRevclerx** [comment]
@Vish-Patil sir, above issue is still getting reproduced on the given PR

![image](https://user-images.githubusercontent.com/102346181/220846370-9a244980-3a10-425b-a72b-f4b6fa61f62f.png)

![image](https://user-images.githubusercontent.com/102346181/220846925-129a6a6e-0255-4c67-a6d7-816d369aadb5.png)

**Comment by PuneetRevclerx** [comment]
@sunrao sir, @Vish-Patil sir, I have checked the above issue on the given branch (https://pr-57006.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have verified above security issue on Acronis Production and now user is not able to add new JS script in Script and Styling and it's working as expected now.

**Comment by prashantjadhav92** [comment]
Thanks, @PuneetRevclerx. I have asked Acronis to verify the fix.

**Comment by prashantjadhav92** [comment]
Hi @PuneetRevclerx @Vish-Patil, Acronis has requested if it is possible to remove the script for all previously created pages as well. For example, https://partners.acronis.com/web/5kjudxww65f8 where JS is still executed

**Comment by Vish-Patil** [comment]
No, its inside page XML. so we can not maniculate it.
