### ISSUE TITLE
#1438743 IDOR allows to send messages to any support case. (01/11/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#6]
Severity: Medium

submit a case then write a message on the case. intercept the request and change the caseid to other case

**Comment by shaileshtayde** [comment]
@prashantjadhav92 The case record can't be accessed by user until it is shared with resp user OR it falls in case permission extension where if user has ability to view all case records  of his current organization.

**Comment by prashantjadhav92** [comment]
@shaileshtayde Acronis has mentioned that this is possible due to this vulnerability. Here are more details on it:

**Vulnerable endpoint: /api/SubmitCaseMessagesForUser. In POST request to this endpoint caseid field might be changed, which will allow to send message to case not related to current user (e.g. created in another organization)**

**Comment by shaileshtayde** [comment]
@prashantjadhav92 we've required permission check added as I mentioned you the criteria above. 
Please get the users using which they have tested this one. So we can confirm the same at our end.

**Comment by PuneetRevclerx** [comment]
@shaileshtayde Sir, I have checked above mention issue and it is possible for a user ("ishant.kshirsagar@revclerx.com") having roles "Platinum Resellers Admins" and "Authorized Service Providers Admins" to send a message in a case created by a user ("anuj.niet2010+01@gmail.com") having role "Registered Resellers Admins". Also both users are in different organizations.

**Comment by HareshKedar** [comment]
@PuneetRevclerx Kindly verify this on acronis2.sb.amp.vg

**Comment by PuneetRevclerx** [comment]
@HareshKedar sir, @sunrao sir, I have checked the above security issue and basic functionality on acronis2.sb.amp.vg and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 Sir, I have verified the above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify.
