### ISSUE TITLE
SEC-4596 Endpoint allows to access all customers files. [/gallery/images/[File_ID]/edit/edit]

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#61]
[File_ID] is numeric and easy to guess. An attacker can access to all files by guessing [File_ID].

Steps To Reproduce:
Login
Visit this URL https://partners.acronis.com/gallery/images/[File_ID]/edit/edit
Type any file id in URL, then click view page source.
The direct URL to download the file is rendered ("original": "https://partners.acronis.com/....)

**Comment by PuneetRevclerx** [comment]
@shaileshtayde Sir, I have checked the above mentioned issue, user can download any image file of the users of any organization by using any file id in the URL.

User: shailesh.tayde@acronis.com

Image id 3856 is not of this user
![image](https://user-images.githubusercontent.com/102346181/174104185-f79e22d3-8df1-4e9c-9283-20776035e43c.png)

**Comment by PuneetRevclerx** [comment]
@shivmishra Sir, I have checked above issue on "https://dvl-pr-50389.amp.vg/". If I use the image id of user from other organization, the page gets blank.
![image](https://user-images.githubusercontent.com/102346181/176167587-2f835b9a-a357-4b60-a98d-3f21e0c319ee.png)

Expected result: There should be error message on the page.
**Note:** Same issue is with document edit as well.

**Comment by shivmishra** [comment]
no thats fine, check you shouldn't be able to download the un-accessible images/documents. i did nothing only corrected the syntax.

**Comment by PuneetRevclerx** [comment]
@sunrao Sir, I have checked above issue and now user is not able to access any un-accessible image or document. It's working fine as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 Sir, I have checked the above mentioned security issue on production and its working as expected now.

**Comment by prashantjadhav92** [comment]
Verified by the client.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx @shivmishra @shaileshtayde Acronis has reported this issue again. Please look into this on priority.

[File_ID] is numeric and easy to guess. An attacker can access to files by guessing [file_ID].

Steps To Reproduce:

* Visit this URL https://partners.acronis.com/html/[File_ID]/0-1/index.html (set [File_ID] to id of file from another organization)

**Comment by PuneetRevclerx** [comment]
As per discussion with Vishal sir, assigned the issue to him

**Comment by Vish-Patil** [comment]
this is nothing but https://github.com/MindMatrix/SecurityTracker/issues/99

its showing template information with same ID.

**Comment by Vish-Patil** [comment]
please get this tested in following PR-60621

**Comment by PuneetRevclerx** [comment]
@sunrao sir, I have checked the above security issue on the given branch (https://pr-60621.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have verified above security issue on Acronis Production and it's working as expected now.

**Comment by sunrao** [comment]
@IshantRevclerx Pl. test this

**Comment by prashantjadhav92** [comment]
@IshantRevclerx @PuneetRevclerx this issue is not resolved on Acronis production.
If you use this URL and change the id, it will display the preview of another user account. https://partners.acronis.com/html/82891/0-1/index.html

**Comment by prashantjadhav92** [comment]
@IshantRevclerx @shaileshtayde can you share the status update on this security issue?

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, I have checked above seurity issue on Acronis Production is working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to confirm.
