### ISSUE TITLE
SEC-3863 H1#1424162 IDOR allows to dump all [admins, customers, users] credentials.

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#62]
Steps To Reproduce
1. Login with your account https://partners.acronis.com/login.
2. Visit this page https://partners.acronis.com/#internalplaybook/45490.
3. Click on ==Email Campaign== and ==Overcoming MSP tool==.

4. Click edit and replace the content with this payload
{{
Email:##user.Email##
Password:##user.password##
}}
5. Click ==Save== and ==Preview==, intercept the request to get preview link.

This is possible with editing any email in the email campaign in playbook.

Impact
The attacker can access all users credentials.

Video is attached.

https://user-images.githubusercontent.com/31324885/171920360-b3635cbc-37ad-4987-a0a0-fbe248aef2bc.mp4

**Comment by prashantjadhav92** [comment]
@cphillips83 @shaileshtayde this is a critical issue.

**Comment by IshantRevclerx** [comment]
@shaileshtayde  Sir, I have Checked above issue and It is not possible to view password of any user in the privew link of the email in the playbook.
![image](https://user-images.githubusercontent.com/92088937/175484064-96195cb2-0eda-425b-b009-3323f3554016.png)

![image](https://user-images.githubusercontent.com/92088937/175484110-a62a9ad3-a422-43f4-9a42-d34f802ce1cb.png)

**Comment by prashantjadhav92** [comment]
@shaileshtayde I have requested Acronis to share more information in case they are able to reproduce this issue.

**Comment by prashantjadhav92** [comment]
Closing this case since the issue is not reproducible.
