### ISSUE TITLE
SEC-4454 IDOR allows to access all customers files. [Via Profileimage Parameter]

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#67]
[profileimage] is numeric and easy to guess. An attacker can access to all files by guessing [profileimage].

1. Go to https://partners.acronis.com/#connections/contacts 
2. When saving contact info intercept call to /api/savecontact
3 Change the profileimage value to any file ID
4. Visit this link view-source:https://partners.acronis.com/connections/contacts/stats/[CONTACT_ID]/
5. Now you will find the document URL

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have Checked above mentioned issue and It is possible to get the document/Images of Users from other organization by following the above mentioned steps.

![ACRONIS--Contact29470](https://user-images.githubusercontent.com/92088937/177254039-600e90bd-72ef-4255-91ef-5907fd910d83.png)

**Comment by MeghanaThakekar** [comment]
@IshantRevclerx @prashantjadhav92 @shaileshtayde - fixed
branch : https://pr-51816.dvl.amp.vg/

**Comment by IshantRevclerx** [comment]
@MeghanaThakekar mam, The above issue is still reproducable on the given branch (https://pr-51816.dvl.amp.vg/)

**Comment by MeghanaThakekar** [comment]
@IshantRevclerx - branch is in build

**Comment by IshantRevclerx** [comment]
@MeghanaThakekar mam, @sunrao Sir, I have checked above security issue and basic functionality on the given branch (https://pr-51816.dvl.amp.vg/) and Its working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have checked above security issue on Acronis production and its working as expected now.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
Verified by the client.
