### ISSUE TITLE
SEC-4800 - IDOR on /collateral/presentation/[id]/info/ API endpoint

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#73]
Description:
IDOR on /collateral/presentation/[id]/info/ API endpoint

1. Login under User1 from Organization1
2. Visit page https://partners.acronis.com/#collateral/presentation
3. Click presentation
4. Copy ID of the created presentation
5. Login under User2 from Organization2
6. Open URL https://partners.acronis.com/#collateral/presentation/[id]/info/ (replace [id] with correct value). See that data is accessible

Fix Requirements: users must not be able to access data of other organizations

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have verified above mentioned Security issue and by following the above mentioned steps , User is able to access data of other organizations.

Url : https://dvl-main.amp.vg/#collateral/presentation
User : Security Ishant (Normal User)
Company Name : Automation Testers

**Comment by Vish-Patil** [comment]
@tajindersharma can you please check this. its related to PPT.

**Comment by sunrao** [comment]
@IshantRevclerx Pl. test this

**Comment by IshantRevclerx** [comment]
@tajindersharma Sir, @sunrao Sir, I have checked above security issue and basic functionality on the given branch ( https://pr-51698.dvl.amp.vg/ ) and Its working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have checked above security issue on Acronis production and its working as expected now.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client to verify this.

**Comment by prashantjadhav92** [comment]
Verified by the client.
