### ISSUE TITLE
SEC-4799 - Stored-XSS via filter input on /#setup/socialdrip/[drip_id]/info/

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#74]
It is possible to create a filter in presentations (https://partners.acronis.com/#manage/campaigns/socialdrip) with XSS payload, which will be rendered and executed on https://partners.acronis.com/#setup/socialdrip/[drip_id]/info/. 

1. Login and copy user's session value and CSRF token from cookies (.ASPXAUTH and X-CSRF-Token)
2. Go to https://partners.acronis.com/#manage/campaigns/socialdrip and create new social drip. Copy ID of this presentation
3. Make the following request (set proper <X-CSRF-Token>, <.ASPXAUTH>, <publishingid> value)

curl -i  -X 'POST' -H 'Content-Type: application/json' -H 'X-Csrf-Token: <X-CSRF-Token>' -H 'X-Requested-With: XMLHttpRequest' -b 'X-CSRF-Token=<X-CSRF-Token>; .ASPXAUTH=<.ASPXAUTH>'  -d '{"publishingid": <publishingid>, "name": "test2", "language": 0, "desc": "", "filters": "abc\"onmouseover=\"confirm(164)\"", "thumbnailid": null, "syndicationcategoryid": null, "isenabled": false}' https://partners.acronis.com/api/SaveSocialTemplate

4. Go to https://partners.acronis.com/#setup/socialdrip/[drip_id]/info/(set proper [drip_id])
5. Move mouse over the filter and see XSS executed

Example: https://partners.acronis.com/#setup/socialdrip/6885/info/

Fix Requirements
Encode untrusted input according to the rendering context

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have verified above mentioned Security Issue and By following the above mentioned steps , JS is getting Executed.

Url : https://dvl-main.amp.vg/#setup/socialdrip/803/info
User : Security Ishant
Company : Automation Testers
![Social Drip---1](https://user-images.githubusercontent.com/92088937/178925262-e42f7de0-61e6-4faa-bd24-70ce2eefdae9.png)

**Comment by sunrao** [comment]
@IshantRevclerx Pl. test this

**Comment by IshantRevclerx** [comment]
@tajindersharma Sir, I have checked above security issue on the given branch ( https://pr-51606.dvl.amp.vg/) JS is not getting executed. but on the Info page, if I try to remove any added filter its not getting removed.

![image](https://user-images.githubusercontent.com/92088937/185562535-a24e78fd-9551-405c-a7fd-83f8e7be0f3c.png)

**Comment by steffisam** [comment]
@IshantRevclerx the issue is fixed can you please check.
url: https://pr-51606.dvl.amp.vg/#manage/campaigns/socialdrip

**Comment by IshantRevclerx** [comment]
@tajindersharma Sir, @sunrao Sir, I have checked above security issue and basic functionality on the given branch ( https://pr-51606.dvl.amp.vg/ ) and Its working as expected now.

**Comment by IshantRevclerx** [comment]
@tajindersharma Sir, @sunrao Sir, As per shiv sir mail I have checked above security issue and basic functionality on this branch (https://pr-52281.dvl.amp.vg/) and its working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify the fix.

**Comment by prashantjadhav92** [comment]
The fix has been verified.
