### ISSUE TITLE
SEC-4801 - IDOR to get email files of any user, /api/importInEmail

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#76]
IDOR to get email files of any user via API endpoint /api/importInEmail

1. Login under
2. Go to https://partners.acronis.com/#communicate/email
3. Start creating email
4. Open browser Developer Tools -> Network
5. Select any favorite template (other template didn't work) and go to email editor
6. See request to /api/importInEmail and copy templateid and emailid
7. Press preview
8. Now make the following request, set proper values for <.ASPXAUTH>, <X-CSRF-Token>, <templateid>, <emailid>

curl -i  -X 'POST' -H 'Content-Type: application/json' -H 'X-Csrf-Token: <X-CSRF-Token>' -H 'X-Requested-With: XMLHttpRequest' -b 'X-CSRF-Token=<X-CSRF-Token>; .ASPXAUTH=<.ASPXAUTH>'  -d '{"templateid":<templateid>,"importtemplateid":90044,"emailid":<emailid>,"webinarid":0}' https://partners.acronis.com/api/importInEmai

{"result":{"newSubjectLine":"hbhbhb","success":true,"theme":"","brandid":0,"isWebinarTemplate":false},"status":0,"version":"368b960820428b2c4f2729c3b10b3319fb6b666c"}

9. See that output contains name of another template
10. Update page with preview (from step 7) and see different content

Fix Requirements
It must not be possible for users to access data of other organizations

**Comment by YogendraMatkar** [comment]
@PuneetRevclerx, @prashantjadhav92 this issue is fixed now, please test it on https://pr-51805.dvl.amp.vg/

**Comment by PuneetRevclerx** [comment]
@Vish-Patil sir, @sunrao sir, I have checked above security issue and basic functionality on the given branch (https://pr-51805.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 Sir, I have checked above security issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
Verified by the client.
