### ISSUE TITLE
SEC-4837 - IDOR on /setup/socialdrip/<id>/info/ API endpoint

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#77]
Description:
IDOR on /setup/socialdrip/<id>/info/ API endpoint

1. Login under User1 from Organization1
2. Visit page https://partners.acronis.com/#manage/campaigns/socialdrip
3. Create social drip
4. Copy ID of the created social drip
5. Login under User2 from Organization2
6. Open URL https://partners.acronis.com/#setup/socialdrip/[drip_id]/info/ (replace [drip_id] with correct value). See that data is accessible

Fix Requirements: users must not be able to access data of other organizations

Video attached:

https://user-images.githubusercontent.com/31324885/179580429-062dd01d-b75e-4847-9c88-ee31e6dbfc03.mp4

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked the above mentioned security issue and it is possible for a user to see the social drip info of the users in other organization by following the above mentioned steps.

User: puneet security
Company: Automation Testers

**Comment by steffisam** [comment]
@PuneetRevclerx The issue is fixed. Can you please check

**Comment by PuneetRevclerx** [comment]
@steffisam @tajindersharma sir, along with normal user, super admin is also not able to see the info of the social drip created by user from other organization. 
Super admin should have access to see the info of the social drip created by user from other organization.

**Comment by steffisam** [comment]
@PuneetRevclerx  I have fixed it. Can you please check.
url: https://pr-51364.dvl.amp.vg/

**Comment by PuneetRevclerx** [comment]
URL: https://pr-51364.dvl.amp.vg/#manage/campaigns/socialdrip
User: puneet Security
Company: Automation Testers

@steffisam I have checked the above issue on given branch. 

- For any Social Drip>> Click on Edit button>> Click on view dropdown and select info
- Model will show "Error 500" on the model.

![image](https://user-images.githubusercontent.com/102346181/184304531-3409d91b-a759-4fcb-b4a5-813eda276fcd.png)

**Comment by steffisam** [comment]
@PuneetRevclerx Sir can u please check it. https://pr-51364.dvl.amp.vg/

**Comment by PuneetRevclerx** [comment]
@sunrao sir, @tajindersharma sir, I have checked the above security issue and basic functionality on given branch (https://pr-51364.dvl.amp.vg/) and its working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, above issue has been resolved and I have verified it on production.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx I was able to reproduce this on Acronis production. Please check again.

**Comment by PuneetRevclerx** [comment]
@tajindersharma sir, I have checked the issue on live and it's working fine 
When a user tries to access social drip of other organization's user then page get's blank.
![image](https://user-images.githubusercontent.com/102346181/186071432-0e692531-f278-439e-96b0-0ea196f23a72.png)

But, on Acronis user is still able to access social drip of other organization's user.
![image](https://user-images.githubusercontent.com/102346181/186071841-2f7b3986-447f-44b8-b2d7-2b6eeab56395.png)

**Comment by tajindersharma** [comment]
@PuneetRevclerx Can you please check if the new release is sent to Acronis. As Acronis release process is different then the other installs.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, release of Acronis was delayed, that's why the issue was reproduceable on Acronis. Now, release of Acronis is pushed and I have verified it on production.

**Comment by prashantjadhav92** [comment]
Thanks, @PuneetRevclerx. I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
Verified by Acronis.
