### ISSUE TITLE
SEC-4855 Reflected XSS on /search page

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#79]
There is reflected XSS on /search page

Steps to reproduce:
Open the following link and see JS executed:
https://partners.acronis.com/search?text=kietna%27;%3C/script%3E%3Cimg%20src=x%20onerror=alert(document.domain);%3E

Fix:
Encode untrusted input according to the rendering context

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked the above mentioned XSS issue and JS is getting executed.

STR:

1. Go to https://main.dvl.amp.vg/#assets-overview
2. Type (</scrip</script>t><img src ?q onerror=prompt(8)>) or (</script><img src?x onerror=alert(document.domain)>) in the search bar and press enter. [**Note: replace "?" after img src with "=" while typing any of the script**]
3. The JS will get executed.

![image](https://user-images.githubusercontent.com/102346181/180134408-8db22e85-df9b-43a2-9c5f-bfaff9f6b676.png)

**Comment by jotdhaliwal** [comment]
@sunrao fixed under #51893

**Comment by PuneetRevclerx** [comment]
@jotdhaliwal sir, @sunrao sir, I have checked above security issue and basic functionality on the given branch (https://pr-51893.dvl.amp.vg/) and it's working as expected now.

**Comment by sunrao** [comment]
@jotdhaliwal Chris has commented on the PR

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 Sir, I have verified the above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
Verified by the client.
