### ISSUE TITLE
#1441100 IDOR allows to close any support ticket, /api/SaveAcronisCaseRecord (01/12/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#8]
Severity: Medium

In the request to API endpoint /api/SaveAcronisCaseRecord it is possible to specify support ticket ID (caseid field), owned by user from another organization and close it

**Comment by shaileshtayde** [comment]
@prashantjadhav92 This has been resolved already adding required permission check;
```
{
    "result": {
        "code": "",
        "message": "user does not have access to case record"
    },
    "status": 1,
    "version": "fd072d5529d5a3e6fc21b04328179a587f326e29"
}
```

**Comment by prashantjadhav92** [comment]
@shaileshtayde I have verified the case is not shared between these users. Nither they have the access to share it.

Case ID is 05398129

**Comment by shaileshtayde** [comment]
@HareshKedar Please confirm the same

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have checked above mention issue and it is possible for a user("ishant.kshirsagar@revclerx.com") having roles "Platinum Resellers Admins" and "Authorized Service Providers Admins" to close a Case created by a user("anuj.niet2010+01@gmail.com") having role "Registered Resellers Admins". Also both users are in different organizations.

**Comment by HareshKedar** [comment]
@IshantRevclerx  Kindly verify this on acronis2.sb.amp.vg

**Comment by IshantRevclerx** [comment]
@HareshKedar Sir, @sunrao Sir, I have checked above security issue and basic functionality on acronis2.sb.amp.vg  and its working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have verified the above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
Confirmed by the client.
