### ISSUE TITLE
XSS: JS getting executed on Lead Routing Page

### ISSUE THREAD

**Issue by PuneetRevclerx** [MindMatrix/SecurityTracker#81]
URL: https://main.dvl.amp.vg/#setup/leadrouting
User: Ishant
Company: Automation Testers

STR:

1. Go to Setup> Lead Routing
2. Click on Create button.
3. Select Distribution based on user
4. In the name field, enter (test "onclick=prompt(8)>"@x.y) or (test "onmouseover=alert(1)//) and finish the form by filling all the required fields.

Actual Result:
If user will add (test "onmouseover=alert(1)//) in the name, JS will execute on hovering the mouse over the name of the lead routing:
![image](https://user-images.githubusercontent.com/102346181/180383695-d4c43140-480d-4654-9784-8d57c9f9520d.png)

If user will add (test "onclick=prompt(8)>"@x.y) in the name, JS will execute on clicking the lead routing name:
![image](https://user-images.githubusercontent.com/102346181/180383882-4cea228f-5a91-464c-b401-6352c771c151.png)

Expected Result: JS should not get executed.

**Comment by HareshKedar** [comment]
@PuneetRevclerx Kindly verify on https://pr-52091.dvl.amp.vg/login

**Comment by PuneetRevclerx** [comment]
@HareshKedar sir, @sunrao sir, I have checked above security issue and basic functionality on the given branch (pr-52091.dvl.amp.vg) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@sunrao sir, @HareshKedar sir, I have verified above issue on mm.amp.vg and it's working as expected now.
