### ISSUE TITLE
XSS: JS is getting executed on MDF fund plan page

### ISSUE THREAD

**Issue by PuneetRevclerx** [MindMatrix/SecurityTracker#82]
URL: https://main.dvl.amp.vg/#manage/mdf/fundplans
User: Ishant
Company: Automation Testers

STR

1. Go to Manage> MDF Approval> MDF Approval Plans
2. Click on create button.
3. In the fund name filed enter (test "onclick=prompt(8)>"@x.y) or (test "onmouseover=alert(1)//) and click on next.
4. Fill any amount in the fields and click on next button.
5. In the activities, click on add button and in the name field enter (test "onclick=prompt(8)>"@x.y) or (test "onmouseover=alert(1)//) and click on save button.
6. Assign the fund plan to any organization and Finish the fund plan.

Actual Result:

1. For the fund plan name:
If user will add (test "onmouseover=alert(1)//) in the fund plan name, JS will execute on hovering the mouse over the name of the fund plan:
![image](https://user-images.githubusercontent.com/102346181/180386963-3485aeea-bef5-4b08-8b6e-6fa4a25c3a72.png)

If user will add (test "onclick=prompt(8)>"@x.y) in the fund plan name, JS will execute on clicking the fund plan name:
![image](https://user-images.githubusercontent.com/102346181/180387249-294a231d-1c65-4c26-a881-424e08acf8df.png)

2. For Activity name: Click on the fund plan and:
If user will add (test "onmouseover=alert(1)//) in the activity name, JS will execute on hovering the mouse over the name of the activity:
![image](https://user-images.githubusercontent.com/102346181/180388026-cd4a875c-08e0-42be-b595-d52620c07c1a.png)

If user will add (test "onclick=prompt(8)>"@x.y) in the activity name, JS will execute on clicking the activity name:
![image](https://user-images.githubusercontent.com/102346181/180388220-3158224e-7e3d-4346-9295-366d4d054af6.png)

Expected result:
JS should not get executed.

**Comment by Vish-Patil** [comment]
@sunrao please get this tested in PR - 51610

**Comment by sunrao** [comment]
@PuneetRevclerx Pl. test this

**Comment by PuneetRevclerx** [comment]
@Vish-Patil sir, I have tested above issue on given branch (https://pr-51610.dvl.amp.vg/). I am not able to add the XSS payload from the UI but, I can add the same payload using the api (/api/UpdateMdfFundPlanInfo) for the fund plan name and (/api/UpdateMdfFundPlanActivity) for the activity name. After sending the request, payload is getting saved and JS is getting executed.

![image](https://user-images.githubusercontent.com/102346181/185555195-460af9cd-cf4b-420c-9e81-d658af076364.png)

- API Request

![image](https://user-images.githubusercontent.com/102346181/185555708-36776583-42ba-4c86-9f9b-6dd800f6ead8.png)

**Comment by Vish-Patil** [comment]
resolved

**Comment by PuneetRevclerx** [comment]
@Vish-Patil sir, @sunrao sir, I have checked the above security issue and basic functionality on the given branch (https://pr-51610.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
Above issue is fixed on main so closing the issue.
