### ISSUE TITLE
XSS-JS getting executed on company Page

### ISSUE THREAD

**Issue by IshantRevclerx** [MindMatrix/SecurityTracker#83]
URL : https://main.dvl.amp.vg/#setup/companies
User : Ishant
Company name : Automation testers

STR : 
1) Go to Setup>>UserManagement>>>Click on Companies
2) In the Companies page, Click on Create button>>>In the company name filed enter (test "onclick=prompt(8)>"@x.y) or (test "onmouseover=alert(1)//) and click on Save Button.

Actual result : 

3) If user will enter (test "onmouseover=alert(1)//) in the company name, JS will execute on hovering the mouse over the name of the  
  company:
![image](https://user-images.githubusercontent.com/92088937/180404157-557a251c-3c8b-4260-90b8-0a3a01a78adb.png)

If user will enter  (test "onclick=prompt(8)>"@x.y) in the name field, JS will execute on clicking the new created company name:
![image](https://user-images.githubusercontent.com/92088937/180405390-2e8b7589-5835-4e56-abee-1625a73e81df.png)

Expected Result : 
JS Should not get executed.

**Comment by shivmishra** [comment]
https://github.com/MindMatrix/AMP/pull/51707
check here

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, @sunrao Sir, I have checked above security issue and basic functionality on the given branch ( https://pr-51707.dvl.amp.vg/ ) and Its working as expected now.
