### ISSUE TITLE
IDOR: User is able to delete MDF fund request created by users from other organizations with /api/DeleteMDFRequest

### ISSUE THREAD

**Issue by PuneetRevclerx** [MindMatrix/SecurityTracker#86]
URL: https://main.dvl.amp.vg/#manage/mdf/funds
User: puneet security
Company: Automation Testers

STR:
In the post request of /api/DeleteMDFRequest, replace MDF fund request id created by users from other organization and send the request. 

Actual Result : MDF fund request will be deleted.
Expected Result : User should not have access to delete MDF fund request created by users from other organization.

**Comment by PuneetRevclerx** [comment]
@Vish-Patil sir, I have checked above security issue on the given branch (https://pr-51825.dvl.amp.vg/) and user is not able to delete MDF fund request created by other organization's user.

But, on the grid of MDF Fund Request and MDF Approval Request page, data is moving out of the page and there is no horizontal scroll available.
![image](https://user-images.githubusercontent.com/102346181/186940587-f73d0577-05e5-4c85-8c9c-3af3afad1a76.png)

**Comment by Vish-Patil** [comment]
@IshantRevclerx is this issue only on this branch or on main as well?

**Comment by PuneetRevclerx** [comment]
@Vish-Patil sir, the above UI Issue is on the main as well.

**Comment by shivmishra** [comment]
@sunrao @IshantRevclerx @shaileshtayde  if API issue fixed then for usability we can create new issue from main instead security issue

**Comment by sunrao** [comment]
@PuneetRevclerx Pl. get Piyush report the UI issue and close the Security issue

**Comment by PuneetRevclerx** [comment]
@Vish-Patil sir, @sunrao sir, I have checked above security issue on the given branch (https://pr-51825.dvl.amp.vg/) and user is not able to delete MDF fund request created by other organization's user.

For the UI, an issue (https://github.com/MindMatrix/AMP/issues/51769) is already created by Priyank on the main.

**Comment by PuneetRevclerx** [comment]
@Vish-Patil sir, I have checked the above issue on Main as the PR was merged and the issue is getting reproduced on Main.

**Comment by PuneetRevclerx** [comment]
@Vish-Patil sir, @sunrao sir, I have checked above security issue on the given branch (https://pr-54081.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@sunrao sir, I have verified it on MM and it's working as expected now.
