### ISSUE TITLE
IDOR : User Can Approve or Reject MDF Fund Request Created by Users from other Organization using /api/UpdateMdfRequest

### ISSUE THREAD

**Issue by IshantRevclerx** [MindMatrix/SecurityTracker#87]
URL : https://main.dvl.amp.vg/#manage/mdf/viewrequests
User : Security Ishant
Company : Automation Testers

STR : 
In the post request of /api/UpdateMdfRequest replaced the id with Fund Plan Request id of any User from other organization. and send the request.
Actual Result : 
MDF Fund Request will be Approved for the MDF plan which is not asssigned to his organization.

![image](https://user-images.githubusercontent.com/92088937/180767723-8603a5b9-84f1-4bcc-8a4d-a2867a5d5da7.png)

Expected Result : 
User Should not be able to Approved the Fund  Request of other Organization

**Comment by Vish-Patil** [comment]
https://github.com/MindMatrix/SecurityTracker/files/9445016/User.and.Org.Permission.based.Deal.Registration.Approval.page.xlsx

**Comment by Vish-Patil** [comment]
please get this checked in following PR- #51916

**Comment by IshantRevclerx** [comment]
@Vish-Patil Sir, I have checked above security issue on the given branch (https://pr-51916.dvl.amp.vg/) and Its working as expected now.
But, the grid is not horizonatly scrolabel and some of the data is moving out of the page.
similar issue is on the other pages of MDF as well.
![image](https://user-images.githubusercontent.com/92088937/187675320-87b36a47-92ba-485a-8fed-1f17bde4de88.png)

**Comment by Vish-Patil** [comment]
@IshantRevclerx is this issue only on this branch or on main as well?

**Comment by IshantRevclerx** [comment]
@Vish-Patil sir, The above UI Issue is on the main as well.

**Comment by Vish-Patil** [comment]
its due to screen size, nothing related to current changes. so please approve this bug and PR.

**Comment by IshantRevclerx** [comment]
@Vish-Patil sir, @sunrao sir, , I have checked above security issue on the given branch (https://pr-51916.dvl.amp.vg/) and user is not able to Approve or Reject MDF request created by other organization's user.

For the UI, an issue (https://github.com/MindMatrix/AMP/issues/51769) is already created by Priyank on the main.

**Comment by IshantRevclerx** [comment]
@Vish-Patil sir and @sunrao sir, working as expected now.
