### ISSUE TITLE
IDOR: User is able to edit deal or contact of a user from other organization

### ISSUE THREAD

**Issue by PuneetRevclerx** [MindMatrix/SecurityTracker#89]
URL: https://main.dvl.amp.vg/#manage/leads/leadregistered or https://main.dvl.amp.vg/#connections/contacts
User: puneet security
Company: Automation Testers

STR:
1. In the payload of /api/savecontact, enter the contact id of other organization's user.
2. Change any information of the contact and send the request.

Actual Result: Contact's information will be changed

Expected Result: User should not have access to edit contact's info of other organization's user.

**Comment by Vish-Patil** [comment]
@shaileshtayde deal is nothing but contact, and save contact API is getting called. so please assign it to respective developer.

**Comment by MeghanaThakekar** [comment]
@IshantRevclerx @prashantjadhav92 @shaileshtayde - fixed
branch : https://pr-51816.dvl.amp.vg/

**Comment by PuneetRevclerx** [comment]
@MeghanaThakekar mam, @sunrao sir, I have checked above security issue and basic functionality on the given branch (https://pr-51816.dvl.amp.vg/) and it's working as expected now.
