### ISSUE TITLE
#1442018 IDOR provides access to files from another organization, /api/CreateEbookFromFile (01/12/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#9]
Severity: Medium

In the request to API endpoint /api/CreateEbookFromFile it is possible to specify ID of any file, including files location in other organizations (field filed). As a result, it is possible to create Ebook from file user should have no access to and read this file.

**Comment by shaileshtayde** [comment]
@prashantjadhav92 This has been addressed by adding resp. permission check. 
Resp. page (https://dvl-main.amp.vg/#collateral/ebook) needs to be tested by @sunrao' team.
@sunrao Please have this page tested on main branch on dvl.

**Comment by sunrao** [comment]
@piyushh Pl. test this on Main

**Comment by piyushh** [comment]
@sunrao +1

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have Verified above issue.and its Working Fine and Its move to Resolved now.
