### ISSUE TITLE
IDOR : User is able to delete deal created by other organization's users

### ISSUE THREAD

**Issue by IshantRevclerx** [MindMatrix/SecurityTracker#90]
URL : https://main.dvl.amp.vg/#manage/leads/leadregistered
User Name : Security Ishant
Company Name : Automation Testers 

STR : 
1) In the post api/DeleteRequest enter the deal registeration ID created by other organization's user.
2) send the request.

Actual Result : The deal regisration request will be deleted.

Expected Result : User should not have access to delete Deal registration Request created by other organization's user.

**Comment by YogendraMatkar** [comment]
@IshantRevclerx, this issue is now fixed, plz test it on https://pr-51641.dvl.amp.vg

**Comment by IshantRevclerx** [comment]
@Vish-Patil Sir, @sunrao Sir, I have checked above security issue and basic functionality on the given branch (https://pr-51641.dvl.amp.vg/ ) and Its working as expected now.

**Comment by YogendraMatkar** [comment]
@sunrao sir, we have added deal access logic as per given rules in https://github.com/MindMatrix/SecurityTracker/files/9320791/User.and.Org.Permission.based.Deal.Registration.Approval.page.xlsx.

can u please assign someone to test this scenarios

**Comment by IshantRevclerx** [comment]
@YogendraMatkar above Issue is again getting reproduce on mm live.

**Comment by YogendraMatkar** [comment]
> @YogendraMatkar above Issue is again getting reproduce on mm live.

@IshantRevclerx, are you still getting this issue, can you please confirm

**Comment by IshantRevclerx** [comment]
@YogendraMatkar, Issue is not reproduced on mm live now. So I am closing the issue.
