### ISSUE TITLE
IDOR: User is able to approve and reject deal registration request created by other organization's user

### ISSUE THREAD

**Issue by PuneetRevclerx** [MindMatrix/SecurityTracker#91]
URL: https://main.dvl.amp.vg/#setup/leads/leadrequests
User: puneet security
Company: Automation Testers

STR:
1. In the payload of /api/ApproveLeadRequest, enter the deal registration id of other organization's user and send the request.
2. Similarly, in the payload of /api/RejectLeadRequest, enter the deal registration id of other organization's user and send the request. 

Actual Result: 
User can accept or reject  the deal registration request.

Expected Result:
User should not have access to accept or reject deal registration request created by other organization's user.

**Comment by Vish-Patil** [comment]
@sunrao so only site/super admin or channel manager of organization can approve/reject deal request.
please approve.

**Comment by sunrao** [comment]
@Vish-Patil 
Site/Super Admins
Channel Manager of the Organization Group who has Deal Admin permission

**Comment by sunrao** [comment]
![image](https://user-images.githubusercontent.com/6465639/184385629-7d15c43d-46d5-4960-9034-a7be621136b4.png)

Make this as a check box in the "Features" as "Deal Admin"

If the check box is checked then based on permission the Deal Approval menu and the deals will be displayed as per the sheet below

[User and Org Permission-based Deal Registration Approval page.xlsx](https://github.com/MindMatrix/SecurityTracker/files/9320791/User.and.Org.Permission.based.Deal.Registration.Approval.page.xlsx)

**Comment by Vish-Patil** [comment]
@sunrao we already have deal permission check in roles.
one is for deal approval and one is for deal  creation

![image](https://user-images.githubusercontent.com/6465635/186837901-8e4d8185-9c72-4c60-ae97-a21d29703cb3.png)

**Comment by sunrao** [comment]
@Vish-Patil Yes we do have, all I am saying is for "Admin" the slider is not needed as the different level like View, edit, doesn't make sense.

This can be worked upon separately

**Comment by Vish-Patil** [comment]
[User and Org Permission based Deal Registration Approval page.xlsx](https://github.com/MindMatrix/SecurityTracker/files/9445016/User.and.Org.Permission.based.Deal.Registration.Approval.page.xlsx)


update permissions

**Comment by Vish-Patil** [comment]
please get this tested on following branch PR-54081

**Comment by PuneetRevclerx** [comment]
@Vish-Patil sir, user is not able to approve the request but user can still reject a lead request created by other organization users.

**Comment by Vish-Patil** [comment]
added security check for deal registration reject as well.

**Comment by PuneetRevclerx** [comment]
@Vish-Patil sir, @sunrao sir, I have checked about the security issue on the given branch (https://pr-54081.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@sunrao sir, I have verified it on MM and it's working as expected now.
