### ISSUE TITLE
IDOR : User can share contact created by other organization's user

### ISSUE THREAD

**Issue by IshantRevclerx** [MindMatrix/SecurityTracker#92]
URL : https://main.dvl.amp.vg/#connections/contacts
User Name : Security Ishant 
Company Name : Automation Testers

STR : 
1) In the Payload api/AddUserToContact enter the contact ID of Other Organization's User 
2) Send the Request

Actual result : The contact will be shared with the user of other organization.

Expected Result : The user should not have access to share the contact created by othe organization's user.

**Comment by MeghanaThakekar** [comment]
@IshantRevclerx  @prashantjadhav92 @shaileshtayde - fixed
branch :  https://pr-51816.dvl.amp.vg/

**Comment by IshantRevclerx** [comment]
@MeghanaThakekar mam, @sunrao Sir, I have checked above security issue and basic functionality on the given branch ( https://pr-51816.dvl.amp.vg/ ) and Its working as expected now.
