### ISSUE TITLE
IDOR : User can edit the opportunity custom field of other organization's user

### ISSUE THREAD

**Issue by IshantRevclerx** [MindMatrix/SecurityTracker#93]
Url : https://main.dvl.amp.vg/#setup/opportunity
User Name : Security Ishant
Company Name : Automation Testers

STR : 
1) In th payload of api/SaveProjectLayout enter the project type id of custom field created by other organization's user
2) change the information and send the request.

Actual Result : Information of the opportunity custom filed will be changed

Expected Result : User should not access to change information of the opportunity custom field created by other organization's user.

**Comment by shivmishra** [comment]
https://github.com/MindMatrix/AMP/pull/51608

fixed in this PR @sunrao @IshantRevclerx

**Comment by IshantRevclerx** [comment]
@shivmishra, @sunrao Sir I have checked above mentioned security tickets on the given branch (https://pr-51608.dvl.amp.vg/), I have also checked basic functionality. and Its working as expected now.
