### ISSUE TITLE
IDOR: User can delete opportunity custom field created by other organization's user.

### ISSUE THREAD

**Issue by PuneetRevclerx** [MindMatrix/SecurityTracker#94]
URL: https://main.dvl.amp.vg/#setup/opportunity
User: puneet security
Company: Automation Testers

STR:
1. In the payload of /api/DeleteProjectTypes, enter the id of custom field created by other organization's user.
2. Send the request.

Actual Result:
Opportunity custom field will be deleted.

Expected Result:
User should not have access to delete opportunity custom field created by other organization's user.

**Comment by shivmishra** [comment]
https://github.com/MindMatrix/AMP/pull/51608

fixed in this PR @sunrao @IshantRevclerx

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, @sunrao sir, I have checked the above security issue on the given branch (https://pr-51608.dvl.amp.vg/) and I have also checked the basic functionality and it's working as expected now.
