### ISSUE TITLE
IDOR: User can delete opportunity records created by other organization's user

### ISSUE THREAD

**Issue by PuneetRevclerx** [MindMatrix/SecurityTracker#95]
URL: https://main.dvl.amp.vg/#manage/opportunity-records
User: puneet security
Company: Automation Testers

STR:
1. In the payload of /api/DeleteProjects, enter the project type id and project id of the opportunity record created by other organization's user.
2. Send the request.

Actual result:
Opportunity record will be deleted.

Expected result:
User should not have access to delete opportunity records created by other organization's user.

**Comment by PuneetRevclerx** [comment]
@shaileshtayde Sir, the opportunity record was not shared with the user and also he didn't had the permission to view other organization's opportunity records.

**Comment by MeghanaThakekar** [comment]
@PuneetRevclerx @prashantjadhav92 - fixed
check on https://pr-51889.dvl.amp.vg/

**Comment by PuneetRevclerx** [comment]
@MeghanaThakekar mam, @sunrao sir, I have checked above security issue and basic functionality on the given branch (https://pr-51889.dvl.amp.vg/) and it's working as expected now.
