### ISSUE TITLE
IDOR : User can copy opportunity records created by other organization's user

### ISSUE THREAD

**Issue by IshantRevclerx** [MindMatrix/SecurityTracker#96]
URL : https://main.dvl.amp.vg/#manage/opportunity-records
User Name : Security Ishant
Company Name : Automation Testers

STR : 
1) In the payload api/CopyProjects enter project type id and project id of opportunity record created by other organization's user
2) Send the request

Actual Result : 
Opportunity record will be copied

Expected Result : 
User should not have access to copy the opportunity records created by other organization's user.

**Comment by MeghanaThakekar** [comment]
@IshantRevclerx @PuneetRevclerx - please check on main

**Comment by IshantRevclerx** [comment]
@MeghanaThakekar mam, I have verified above security issue on main and Its working as expected now.

**Comment by IshantRevclerx** [comment]
@sunrao Sir, I have checked above security issue on production and Its working as expected now.
