### ISSUE TITLE
IDOR : User can edit opportunity records created by other organization's user

### ISSUE THREAD

**Issue by IshantRevclerx** [MindMatrix/SecurityTracker#97]
URL : https://main.dvl.amp.vg/#manage/opportunity-records
User Name : Security Ishant
Company Name : Automation Testers

STR : 
1) In the payload api/SaveProject enter projecttypeid and projectid of opportunity records created by other organization's user.
2) Edit opportunity record details and Send the Request.

Actual Result : 
Details of opprtunity records will be changed

Expected Result : 
User should not have access to edit opportunity records created by other organization's user.

**Comment by MeghanaThakekar** [comment]
@shaileshtayde @sunrao - 
We have check where If logged in user has project view permission and logged in user's current company id is similar to the project id then we are allowing to access the project.
What are the permission need to add?
![image](https://user-images.githubusercontent.com/6465588/186446160-2c121eec-dd87-4ebc-a65b-22b1e540fcac.png)

**Comment by shaileshtayde** [comment]
@pKanth can you please comment on the same.

**Comment by sunrao** [comment]
@shaileshtayde @MeghanaThakekar 
If the Opportunity Type is "Public" then Channel Managers/Super Admin/Site Admins can see the Opportunity records

If the Opportunity Type is "Non-Public" then only those whom the Opportunity is shared/Super Admin/Site Admin

**Comment by MeghanaThakekar** [comment]
@IshantRevclerx @PuneetRevclerx - please check on main

**Comment by IshantRevclerx** [comment]
@MeghanaThakekar mam, I have checked above security issue on main and It's working as expected now.

**Comment by IshantRevclerx** [comment]
@sunrao Sir, I have checked above security issue on production and Its working as expected now.
