### ISSUE TITLE
SEC-4861 - IDOR on /api/GetActivityFeed

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#98]
IDOR is possible in POST request to /api/GetActivityFeed  via contactid parameter allowing to access information about contacts from another organization

Steps to Reproduce:
Go to URL: https://partners.acronis.com/#communicate/email, then click to sent email
In the Views dropdown click to Recipients. At this moment POST request will be sent to /api/GetActivityFeed
In this POST request change isroutedlead parameter from false to true, and contactid parameter to ID of any contact from another organization. See information about this contact in server response
Fix: It must not be possible to access data related to other organizations

Score - [AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N&version=3.1)

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I tried reproducing the above mentioned security issue by following the mentioned steps, but I didn't get any response from the sever. 

![get activity feed](https://user-images.githubusercontent.com/102346181/183892276-c35f1a5a-0f8e-421b-be70-a02a8a7cb9b0.png)


Kindly provide more information about the issue so that I can reproduce it at my end.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx I have asked the client for additional details.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx here are more details from the client. Can you please check these?
It is possible to make this request manually and obtain data. The request is the following (it is required to set correct <SESSION>, <CSRF_TOKEN> for currently logged in user. 

Here is example of the test client performed:

{"result":{"feed":"[{\"msg\":\"opened email <span class='keyword'><a class='keyword' href='[https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj'](https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj%27) target='_blank'>new email</a></span>\",\"when\":\"7/22/2022 2:30:58 PM UTC\",\"type\":\"email\",\"count\":19},{\"msg\":\"opened email <span class='keyword'><a class='keyword' href='[https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj'](https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj%27) target='_blank'>new email</a></span>\",\"when\":\"7/21/2022 11:51:57 PM UTC\",\"type\":\"email\",\"count\":19},{\"msg\":\"opened email <span class='keyword'><a class='keyword' href='[https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj'](https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj%27) target='_blank'>new email</a></span>\",\"when\":\"7/21/2022 11:50:26 PM UTC\",\"type\":\"email\",\"count\":19},{\"msg\":\"opened email <span class='keyword'><a class='keyword' href='[https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj'](https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj%27) target='_blank'>new email</a></span>\",\"when\":\"7/21/2022 2:32:25 PM UTC\",\"type\":\"email\",\"count\":19},{\"msg\":\"clicked link <span class='keyword'>https:/&#8203;/&#8203;partners.acronis.com/&#8203;file/&#8203;ddvojljzq5z8k/&#8203;Data-Sheet-Acronis-Cyber-Protect-Cloud-Advanced-DLP-EN-US-220427.pdf?userid=coqfj9fjr1l2d</span> in email <span class='keyword'><a class='keyword' href='[https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj'](https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj%27) target='_blank'>new email</a></span>\",\"when\":\"7/21/2022 2:26:53 PM UTC\",\"type\":\"email\",\"count\":19},{\"msg\":\"opened email <span class='keyword'><a class='keyword' href='[https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj'](https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj%27) target='_blank'>new email</a></span>\",\"when\":\"7/21/2022 2:26:31 PM UTC\",\"type\":\"email\",\"count\":19},{\"msg\":\"opened email <span class='keyword'><a class='keyword' href='[https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj'](https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj%27) target='_blank'>new email</a></span>\",\"when\":\"7/21/2022 8:37:31 AM UTC\",\"type\":\"email\",\"count\":19},{\"msg\":\"clicked link <span class='keyword'>https:/&#8203;/&#8203;partners.acronis.com/&#8203;file/&#8203;ddvojljzq5z8k/&#8203;Data-Sheet-Acronis-Cyber-Protect-Cloud-Advanced-DLP-EN-US-220427.pdf?userid=coqfj9fjr1l2d</span> in email <span class='keyword'><a class='keyword' href='[https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj'](https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj%27) target='_blank'>new email</a></span>\",\"when\":\"7/21/2022 8:34:26 AM UTC\",\"type\":\"email\",\"count\":19},{\"msg\":\"opened email <span class='keyword'><a class='keyword' href='[https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj'](https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj%27) target='_blank'>new email</a></span>\",\"when\":\"7/21/2022 8:34:09 AM UTC\",\"type\":\"email\",\"count\":19},{\"msg\":\"opened email <span class='keyword'><a class='keyword' href='[https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj'](https://partners.acronis.com/html/91994/0-1/index.html?userid=coqfj9fjr1l2d&cid=cmu9gvzmovjdj%27) target='_blank'>new email</a></span>\",\"when\":\"7/21/2022 8:34:09 AM UTC\",\"type\":\"email\",\"count\":19}]"},"status":0,"version":"f657a7a8e15b2290478b958d688e19d5f894fb64"}

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked the above issue and it's working fine now. User is not able to access the info of contacts created by other organization's users.
![image](https://user-images.githubusercontent.com/102346181/186472017-dee7fe11-fac9-42ce-add7-697ee4319ad8.png)

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx is this verified on Acronis production?

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 Yes Sir. 
![image](https://user-images.githubusercontent.com/102346181/186479942-1e618f07-9516-4add-8667-ba70d3f486f7.png)

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx I have shared the update with the client.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx the client has mentioned this is not fixed yet.
Logged in user - 

Contact with id 517612 and email address [stushieva@wearehackerone.com](mailto:stushieva@wearehackerone.com). Request example:

curl https://partners.acronis.com/api/GetActivityFeed -X POST -H "Content-Type: application/json" -H "X-CSRF-Token: <CSRF_TOKEN>" -b ".ASPXAUTH=<SESSION>"-d '{"contactid":517612,"pagesize":10,"page":0,"activitytype":0,"isroutedlead":true}'

{"result":{"feed":"[{\"msg\":\"user <span class='keyword'>[anastasia.doronina@acronis.com.sg](mailto:anastasia.doronina@acronis.com.sg)</span> unsubscribed\",\"when\":\"9/7/2022 2:10:46 PM UTC\",\"type\":\"contact\",\"count\":1}]"},"status":0,"version":"8ca1176cb00d1c74fd000d84f29621edf458b748"}

**Comment by shaileshtayde** [comment]
@PuneetRevclerx @IshantRevclerx Please give a run on this one as well. You'd see the existing record because it might have been created due to contact check wasn't present in resp. API before.

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, @sunrao sir, I have checked the above security issue on the Main and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis Production and it's working as expected now. As mentioned by Shailesh sir, records created earlier will stay accessible but new records will not be accessible to any user.

**Comment by prashantjadhav92** [comment]
This is approved to be fixed.
